### ISSUE TITLE
npm install of nodejs javascript-client - Invalid version

### ISSUE THREAD

**Issue by junaidahmed361** [Azure-Samples/cognitive-services-speech-sdk#1042]
I have followed the procedure to install the batch transcription REST api from Swagger for nodejs, but I keep getting the error "npm ERR! Invalid version: "v3.0". The npm logs don't give much more info other than this as well. I have created a directory called 'nodejs' and while in the directory, I am attempting to install the packages from the downloaded javascript client directory using `npm install path/to/javascript-client`. 

How can I fix this issue? I have tried keeping version as just "3.0" as well to no luck.

```
Here is the npm log:
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '/Users/myuser/Downloads/javascript-client'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.15.5
4 verbose config Skipping project config: /Users/myuser/.npmrc. (matches userconfig)
5 verbose npm-session a4d6c32f0a345f5d
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for file:/Users/myuser/Downloads/javascript-client Invalid version: "v3.0"
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 118ms
11 verbose stack Error: Invalid version: "v3.0"
11 verbose stack     at Object.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:191:13)
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
11 verbose stack     at Array.forEach (<anonymous>)
11 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
11 verbose stack     at new Manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:116:3)
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:52:13
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
11 verbose stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:611:10)
11 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
11 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at processImmediate (internal/timers.js:461:21)
12 verbose cwd /Users/myuser/Documents2/nodejs
13 verbose Darwin 20.2.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "/Users/myuser/Downloads/javascript-client"
15 verbose node v14.15.5
16 verbose npm  v6.14.11
17 error Invalid version: "v3.0"
18 verbose exit [ 1, true ]
```

**Comment by chlandsi** [comment]
I can repro this with newer versions of npm. Please try changing the value for `version` in the package.json of the generated client to `3.0.0` to be a proper semantic version.

**Comment by junaidahmed361** [comment]
Actually it was a node version issue. After upgrading my node and npm it worked
