### ISSUE TITLE
Get the dll load error in windows server

### ISSUE THREAD

**Issue by loooog** [Azure-Samples/cognitive-services-speech-sdk#1049]
Hi,
I am using the java SDK . It works well in local and other windows machine. But when deployed to window server I got this:
(JDK 11, windows server 2019 64-bit)

> Could not copy external Speech SDK libraries because of the following error: null
> 2021-04-21 11:04:33.247 ERROR 8244 --- [nio-8071-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.fromSubscription(Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;Ljava/lang/String;)J] with root cause
> 
> java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.fromSubscription(Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;Ljava/lang/String;)J
>         at com.microsoft.cognitiveservices.speech.SpeechConfig.fromSubscription(Native Method) ~[client-sdk-1.13.0.jar!/:na]
>         at com.microsoft.cognitiveservices.speech.SpeechConfig.fromSubscription(SpeechConfig.java:103) ~[client-sdk-1.13.0.jar!/:na]

**Comment by chschrae** [comment]
Hi @loooog ,

Thanks for posting your issue.

It definitely appears that it cannot find the dlls or native libraries of the SDK.

Can you share more details about how your project is organized?
Are you using maven or gradle to include the SDK?
Have you tried updating to the newest version? (1.16)
What are the details of the other windows environments that it does work on?
