### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()

### ISSUE THREAD

**Issue by grale88** [Azure-Samples/cognitive-services-speech-sdk#112]
I am developing a Java application that uses speech SDK. Dependancy is added through pom.xml as described on documentation site. Upon code executing I get UnsatisfiedLinkError when trying to create WavStream. 

Part of the stack trace:
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()V
	at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init(Native Method)
	at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.<clinit>(carbon_javaJNI.java:494)
	at com.microsoft.cognitiveservices.speech.internal.PullAudioInputStreamCallback.<init>(PullAudioInputStreamCallback.java:62)
	at com.microsoft.cognitiveservices.speech.audio.PullAudioInputStreamCallback$PullAudioInputStreamCallbackAdapter.<init>(PullAudioInputStreamCallback.java:19)
	at com.microsoft.cognitiveservices.speech.audio.PullAudioInputStreamCallback.<init>(PullAudioInputStreamCallback.java:13)
	at ai.aiconix.cox.speechtotext.WavStream.<init>(WavStream.java:15)

The same thing happens when running on both Ubuntu and Windows.
Latest SDK version is used

**Comment by fmegen** [comment]
Currently, the Speecj SDK is only supported on 64bit.

Are you sure you are running on a 64bit system and 64bit java vm?

as for java, adding "-d64" should select the correct vm in cases where you have both, 32bit and 64bit environments installed.

please try "java -d64 -version" and make sure the output contains "64-bit VM"

**Comment by mahilleb-msft** [comment]
Yes, it may be possible. Would you be able to try out Java 8 ?

**Comment by fmegen** [comment]
Hi @grale88,

sorry for the delay.

One question, did you create the speechconfig before creating the wav file adapter?

Could you please make sure that you call

   SpeechConfig.fromSubscription(KEY, REGION)

(or one of the other from*() functions before creating your stream class).

The reason is that the speech sdk internally loads the native dll only at the "entry" classes automatically, like SpeechConfig, or Recognizer classes.

please give that a try and see if that helps.

thanks!

**Comment by grale88** [comment]
> Could you please make sure that you call SpeechConfig.fromSubscription(KEY, REGION)
(or one of the other from*() functions) at least once before creating your stream class.

This was a key part. We had creating of AudioConfig and WavStream just before creating SpeechConfig. When we changed the order everything went fine. As a suggestion, if possible, it would be very good if there is some kind of dependency in this case to force the developer to first create SpeechConfig instance. 

@fmegen @mahilleb-msft  Thank you for the help! 👍

**Comment by javajared** [comment]
Can confirm the same is true when using the SDK for Android as well. Thanks everyone for your insight

**Comment by nitinkumar2512** [comment]
I have tried Speech SDK and it worked fine on Ubuntu (16.04 & 18.04) & Windows which are in office premise, however, the same code is not working when tried to run on CentOS 7, RHEL 7 and Ubuntu 16.04 (launched in AWS) and got below exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()V
	at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init(Native Method)
	at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.<clinit>(carbon_javaJNI.java:517)
	at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:69)
	at azure.speech.SpeechToText.recognitionWithAudioFile(SpeechToText.java:93)
	at azure.speech.SpeechToText.main(SpeechToText.java:69)


All the environments and Java are of 64bit and Speech SDK version is of 1.2.0
Am I missing something here or Speech SDK does not have support for above mentioned OS's. Any help would be appreciable.

**Comment by mahilleb-msft** [comment]
@nitinkumar2512 - we currently only support Ubuntu 16.04 and 18.04 as Linux distributions. So, CentOS 7 or RHEL 7 will not currently work. Ubuntu 16.04 on AWS, however, should work .. can you double-check that you've installed the required dependencies (cf. https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-java-jre#prerequisites)?

**Comment by mahilleb-msft** [comment]
Closing this one .. if it doesn't work in the Ubuntu 16.04 case on AWS after installing the required dependencies, please re-open or open a new issue.

Thanks, Mark

**Comment by nitinkumar2512** [comment]
@mahilleb-msft It worked, Thanks for the help.
