### ISSUE TITLE
App crashes when build in release mode after enabling minification.

### ISSUE THREAD

**Issue by PradeepAmradi** [Azure-Samples/cognitive-services-speech-sdk#115]
**Describe the bug**
![screenshot_20181206-133140](https://user-images.githubusercontent.com/7258223/49569966-6c5a5680-f95b-11e8-997d-baf4b45e03b5.jpg)

App crashes when build in release mode after enabling minification.

**To Reproduce**
1. enable pro-guard, set minifyEnabled to true in app module build.gradle file
2. build the app in release mode and try installing the app.

**Expected behavior**
Expected that app will be launched and is actionable

**Version of the Cognitive Services Speech SDK**
1.1.2

**Platform, Operationg System, and Programming Language**
 - OS: Android
 - Hardware - ARM

**Additional context**
 - stack trace below
2018-12-06 12:27:50.210 27663-27663/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.cognitiveservices.speech.samples.sdkdemo, PID: 27663
    java.lang.NoSuchMethodError: no static method "Lcom/microsoft/cognitiveservices/speech/internal/carbon_javaJNI;.SwigDirector_PullAudioInputStreamCallback_Read(Lcom/microsoft/cognitiveservices/speech/internal/PullAudioInputStreamCallback;[B)I"
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init(Native Method)
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.<clinit>(Unknown Source:0)
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.SetTempDirectory(Native Method)
        at com.microsoft.cognitiveservices.speech.i.<clinit>(Unknown Source:33)
        at com.microsoft.cognitiveservices.speech.i.a(Unknown Source:0)
        at com.microsoft.cognitiveservices.speech.samples.sdkdemo.MainActivity.onCreate(Unknown Source:139)
        at android.app.Activity.performCreate(Activity.java:7041)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by PradeepAmradi** [comment]
This issue can be resolved by specifying a pro-guard rule below, which specifies the compiler not to obfuscate the whitelisted classes/methods

**Include below rule in your pro-guard.pro file**
 -keep public class com.microsoft.cognitiveservices.** {
    public protected *;
 }

**Comment by fmegen** [comment]
Thank you for reporting the issue

We will include correct pro-guard rules in the next version of the sdk (1.2.0) so you wont need the above fix anymore.
