### ISSUE TITLE
report an error at the beginning

### ISSUE THREAD

**Issue by 448147876** [Azure-Samples/cognitive-services-speech-sdk#1193]
Describe the bug
We use com.microsoft.cognitiveservices.speech:client-sdk:1.18.0 ,report an error at the beginning.

To Reproduce
1. fill in speech-key and speech-location
2. run

Expected behavior
**

Version of the Cognitive Services Speech SDK
1.18.0

Platform, Operating System, and Programming Language
 - OS: MacOS big sur
 - Hardware - M1
 - Programming language: Java

**Additional context**
 - run:
      SpeechConfig speechConfig = SpeechConfig.fromSubscription("**", "https://southeastasia.customvoice.api.speech.microsoft.com/");
 - error:
     Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
	at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
	at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:77)
	at com.ruoyi.wx.controller.DemoController.main(DemoController.java:15)
![1627888818701](https://user-images.githubusercontent.com/34055531/127820117-a7190d37-80e1-4309-a242-78aa120f160e.jpg)

**Comment by yulin-li** [comment]
relate #1025

**Comment by yulin-li** [comment]
Hi @448147876 thanks for reaching out. The SDK version 1.18 doesn't support apple silicon for now. You can try to use it with an Intel chip machine, or use Linux/Windows.
