### ISSUE TITLE
Using batch Speech Ingestion. Fails on every OTHER file, (with a 401)

### ISSUE THREAD

**Issue by Markyboy944** [Azure-Samples/cognitive-services-speech-sdk#1208]
**Describe the bug**
I have set up my Azure batch ingestion environment using the Batch ARM template. I am carefully dragging and dropping WAV files into the "audio-input" folder (using azure storage explorer). (Note -I am not changing anything about my speech service endpoint/keys, or indeed anything else). [Note wav files are just a few seconds in length. Longest is less than 10 seconds]

This is what happens:
- it works
- next attempt (it fails)
- next attempt (it works)
- next attempot (it fails) 
- [etc]

The "failure" results in no json file being produced, and a log in the "error-report" folder (See "Error Message" at bottom of this post).

**To Reproduce**
Try dragging/dropping a wav file. Let it process. See if it works (i.e. gets properly transcribed, and relevant json file appears in "json-result-output". If it works, try similar, see if it fails (etc)

**Expected behavior**
It should work every time, rather than every other time.

**Error message**
Exception Connector.HttpStatusCodeException: PermissionDenied: {"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}
   at Connector.HttpResponseMessageExtensions.EnsureSuccessStatusCodeAsync(HttpResponseMessage responseMessage) in C:\Users\a-javan\Desktop\repos\cognitive-services-speech-sdk\samples\batch\batch-ingestion-client\Connector\Extensions\HttpResponseMessageExtensions.cs:line 23
   at Connector.BatchClient.SendHttpRequestMessage(HttpRequestMessage httpRequestMessage, TimeSpan timeout) in C:\Users\a-javan\Desktop\repos\cognitive-services-speech-sdk\samples\batch\batch-ingestion-client\Connector\BatchClient.cs:line 119
   at Connector.BatchClient.GetAsync[TResponse](String path, String subscriptionKey, TimeSpan timeout) in C:\Users\a-javan\Desktop\repos\cognitive-services-speech-sdk\samples\batch\batch-ingestion-client\Connector\BatchClient.cs:line 105
   at FetchTranscriptionFunction.TranscriptionProcessor.ProcessTranscriptionJobAsync(TranscriptionStartedMessage serviceBusMessage, ILogger log) in C:\Users\a-javan\Desktop\repos\cognitive-services-speech-sdk\samples\batch\batch-ingestion-client\FetchTranscription\TranscriptionProcessor.cs:line 48 in job 2021-08-11T05:26:00_0 at https://uksouth.api.cognitive.microsoft.com/speechtotext/v3.0/Transcriptions/4db180d8-6fb5-47cc-8fc8-18a25f5f434b: PermissionDenied: {"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}

**Comment by zhouwangzw** [comment]
@HenryvanderVegte Could you please help? Thanks!

**Comment by HenryvanderVegte** [comment]
Hi,

sadly I can't reproduce the error on my side..
We are always getting the subscription key from the same environment variable inside of the function (https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs, l.38) - did you by any chance update the subscription key inside of the key vault that was deployed as part of the solution (the AzureSpeechServicesKey secret)? It might be that one instance of the function still has the old value cached. If that's the case, restarting the FetchTranscriptionFunction might help.

Could you please also check if the Key Vault Reference in your FetchTranscriptionFunction is still working fine (FetchTranscriptionFunction->Settings->Configuration->Application Settings)?
![Cap2](https://user-images.githubusercontent.com/12466089/128995863-3e2d3324-be6a-4a49-a9dd-b338c59e53f7.PNG)

Thanks!

**Comment by HenryvanderVegte** [comment]
No response from user, closing issue for now.
