### ISSUE TITLE
ModuleNotFoundError: No module named '_speech_py_impl'

### ISSUE THREAD

**Issue by hjain5164** [Azure-Samples/cognitive-services-speech-sdk#1367]
**Describe the bug**
I am trying to use the Speech SDK for Python but while import the package using the statement `import azure.cognitiveservices.speech as speechsdk`, I am getting error.

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Programming language: Python

**Additional context**
Below is the complete error trace that I am getting:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
    from .speech import *
  File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 17, in <module>
    _speech_py_impl = swig_import_helper()
  File "/usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 16, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_speech_py_impl'
```

**Comment by pankopon** [comment]
@hjain5164 This is the reason:
```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/lib/python3.7/dist-packages/azure/cognitiveservices/speech/_speech_py_impl.so)
```
Are you using a [supported Linux distribution](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk)? E.g. on Ubuntu 18.04.5 LTS
```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
...
CXXABI_1.3.11
```

**Comment by pankopon** [comment]
Closed as answered, please open a new issue if more support is needed.
