### ISSUE TITLE
Unable to load shared library 'Microsoft.CognitiveServices.Speech.csharp.bindings.dll

### ISSUE THREAD

**Issue by michael-chi** [Azure-Samples/cognitive-services-speech-sdk#143]
**Describe the bug**
Deploying an ASP.Net core web application to with Speech SDK to a Linux container, get below error at runtime
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'Microsoft.CognitiveServices.Speech.csharp.bindings.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMicrosoft.CognitiveServices.Speech.csharp.bindings.dll: cannot open shared object file: No such file or directory
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_carbon_csharp(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SWIGExceptionHelper..ctor()
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.new_PullAudioInputStreamCallback()
   at Microsoft.CognitiveServices.Speech.Internal.PullAudioInputStreamCallback..ctor()
   at Microsoft.CognitiveServices.Speech.Audio.PullAudioInputStreamCallbackInternalAdapter..ctor(PullAudioInputStreamCallback callback)
   at Microsoft.CognitiveServices.Speech.Audio.PullAudioInputStreamCallback..ctor()
   at SignalRChat.Stream.VoiceAudioStream..ctor() in /appsrc/Stream/AudioStream.cs:line 13
   at SignalRChat.Hubs.VoiceHub.RegisterAttendeeAsync(String name, String myLanguage, String preferredLanguage) in /appsrc/Hubs/VoiceHub.cs:line 54
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Dockerfile
```
# 3.0.0-preview-aspnetcore-runtime
From microsoft/dotnet:3.0.100-preview-sdk

RUN mkdir /appsrc  

COPY . /appsrc

WORKDIR /appsrc
RUN echo $(ls)
RUN dotnet restore
RUN dotnet build

EXPOSE 5001
EXPOSE 5000

CMD ["dotnet","run"]

```

.csproj file
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UserSecretsId>b663f109-4cec-4eb1-a707-0b191626fafa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="APP_DATA\dummy.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="APP_DATA\dummy.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="3.0.0-preview-18579-0056"/>
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="3.0.0-preview-18579-0056" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="3.0.0-preview-18579-0056" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="3.0.0-preview.18572.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.0.0-preview.18572.1" />    
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="3.0.0-preview.18572.1" />     
    <!-- <PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="2.2.0" /> -->
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="3.0.0-preview-18579-0056" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.0.0-preview.18572.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

check output folder there is not "Microsoft.CognitiveServices.Speech.csharp.bindings.dll" in linux-x64 folder

**To Reproduce**
1. ssh into a Linux machine (Ubuntu 16.0.6)
2. run docker build . -t name:tag
3. run docker run -p 5000:5000

**Expected behavior**
Should install package with Microsoft.CognitiveServices.Speech.csharp.bindings.dll

**Version of the Cognitive Services Speech SDK**
1.2.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - Ubuntu 16.0.4
 - Hardware - x64
 - Programming language: ASP.Net core 3.0.0 preview/C#

**Comment by mahilleb-msft** [comment]
Sorry, at this stage it's expected, since the Docker image you're using is based on Debian 9, while the Speech SDK only currently support Ubuntu 16.04 and 18.04 on Linux.

**Comment by wolfma61** [comment]
closing for now...

**Comment by mahilleb-msft** [comment]
@michael-chi  - Speech SDK 1.5.0 adds support for Debian 9 (or Debian 9 based Docker images). Please give it a try.

**Comment by kierenj** [comment]
To confirm: the official `mcr.microsoft.com/dotnet/core/aspnet:3.0` doesn't support Speech SDK. Is there a recommended alternative official image?

**Comment by robinmanuelthiel** [comment]
Please reopen.

According to @mahilleb-msft, Ubuntu 18.04 works fine.

> Sorry, at this stage it's expected, since the Docker image you're using is based on Debian 9, while the Speech SDK only currently support Ubuntu 16.04 and 18.04 on Linux.

But when using the `mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic` image ([which runs on Ubuntu 18.04](https://hub.docker.com/_/microsoft-dotnet-core-aspnet/)). The same error occurs.

**Comment by smiranda** [comment]
Thanks @kierenj , This worked on the docker image ` mcr.microsoft.com/dotnet/core/sdk:3.1-bionic`  : 
> ```
> RUN apt-get update
> RUN apt-get -y install build-essential libssl1.0.0 libasound2 wget
> ```

**Comment by MarcusKohnert** [comment]
This worked for me:

```
FROM mcr.microsoft.com/dotnet/aspnet:9.0-bookworm-slim

RUN apt-get update
RUN apt-get -y install build-essential ca-certificates libasound2-dev libssl-dev wget
```
