### ISSUE TITLE
In the case of weak networks, anomalies may occur, leading to flip-flop

### ISSUE THREAD

**Issue by shaohui93** [Azure-Samples/cognitive-services-speech-sdk#145]
**Describe the bug**

**To Reproduce**
1. Turn on speech recognition.
2.Stop Speech Recognition
3.Wait for some time, no stop callback, and then an exception occurs.

**Expected behavior**
It is hoped that when speech recognition is stopped, callbacks for stop recognition can be triggered quickly.

**Version of the Cognitive Services Speech SDK**
'com.microsoft.cognitiveservices.speech:client-sdk:1.2.0'

**Platform, Operating System, and Programming Language**
 Android  ARM   JAVA

**Additional context**
 E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: com.transn.onemini, PID: 25828
    java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize() timed out after 20 seconds
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.delete_Recognizer(Native Method)
        at com.microsoft.cognitiveservices.speech.internal.Recognizer.delete(Recognizer.java:32)
        at com.microsoft.cognitiveservices.speech.internal.TranslationRecognizerBase.delete(TranslationRecognizerBase.java:37)
        at com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.delete(TranslationRecognizer.java:37)
        at com.microsoft.cognitiveservices.speech.internal.TranslationRecognizer.finalize(TranslationRecognizer.java:26)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:239)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:226)
        at java.lang.Thread.run(Thread.java:761)

**Comment by shaohui93** [comment]
> 你怎么停止认可？你只是破坏识别器，或者......？
> 
> 在标题中你提到'弱网络'，你是否通过有线连接实现了不同的行为？
> 
> THX 
> 沃尔夫冈

I use  recognizer.stopContinuousRecognitionAsync()         to stop
