### ISSUE TITLE
java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)' - Java CentOS 7

### ISSUE THREAD

**Issue by floringolintchi** [Azure-Samples/cognitive-services-speech-sdk#1461]
Hello,

My application is a spring boot java project connecting to the azure services for converting speech to text, analyzing sentiment and translating. I am trying to deploy my application to a centos 7 VM, but I get the error in the title when calling the my application endpoint converting speech to text. I have no problem running the application from my local windows 10 machine. Here are my logs:

```
:: Spring Boot ::                (v2.5.2)

2022-04-08 13:35:27.482  INFO 30261 --- [           main] .e.t.f.m.ExtractTextFromMediaApplication : Starting ExtractTextFromMediaApplication v0.0.1-SNAPSHOT using Java 11.0.14.1 on speech2text..net with PID 30261 (/usr/local/speech2text/extractTextFromMedia-0.0.1-SNAPSHOT.jar started by root in /export/home/fos)
2022-04-08 13:35:27.497  INFO 30261 --- [           main] .e.t.f.m.ExtractTextFromMediaApplication : No active profile set, falling back to default profiles: default
2022-04-08 13:35:29.701  INFO 30261 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8443 (https) 8080 (http)
2022-04-08 13:35:29.724  INFO 30261 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-04-08 13:35:29.725  INFO 30261 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.48]
2022-04-08 13:35:29.792  INFO 30261 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-04-08 13:35:29.792  INFO 30261 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2186 ms
2022-04-08 13:35:30.925  INFO 30261 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-04-08 13:35:31.336  INFO 30261 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8443 (https) 8080 (http) with context path ''
2022-04-08 13:35:31.363  INFO 30261 --- [           main] .e.t.f.m.ExtractTextFromMediaApplication : Started ExtractTextFromMediaApplication in 4.656 seconds (JVM running for 5.295)
2022-04-08 13:35:36.283  INFO 30261 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-04-08 13:35:36.284  INFO 30261 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-04-08 13:35:36.285  INFO 30261 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-04-08 13:35:36.821  INFO 30261 --- [nio-8080-exec-1] c.r.c.e.t.f.m.s.TextFromMediaService     : 20220408133536_videoplayback.mp4 video file was coppied on disk.
2022-04-08 13:35:36.995  INFO 30261 --- [nio-8080-exec-1] c.r.c.e.t.f.m.s.TextFromMediaService     : Audio file created in path: /tmp/temp_audio/20220408133536_videoplayback_20220408133536.wav
2022-04-08 13:35:37.077 ERROR 30261 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)'] with root cause
 
java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)'
        at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method) ~[client-sdk-1.19.0.jar!/:na]
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:77) ~[client-sdk-1.19.0.jar!/:na]
        at com...extract.text.from.media.service.ExtractTextFromAudioService.getSpeechConfig(ExtractTextFromAudioService.java:102) ~[classes!/:0.0.1-SNAPSHOT]
        at com...extract.text.from.media.service.ExtractTextFromAudioService.continuousRecognitionWithFileWithPhraseListAsync(ExtractTextFromAudioService.java:32) ~[classes!/:0.0.1-SNAPSHOT]
        at com...extract.text.from.media.service.TextFromMediaService.getTextFromMediaFile(TextFromMediaService.java:89) ~[classes!/:0.0.1-SNAPSHOT]
        at com...extract.text.from.media.service.TextFromMediaService.getTextFromMedia(TextFromMediaService.java:72) ~[classes!/:0.0.1-SNAPSHOT]
        at com...extract.text.from.media.controller.MediaToTextMultipartController.extractTextFromMedia(MediaToTextMultipartController.java:28) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.5.2.jar!/:2.5.2]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

This is my pom file:
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns=http://maven.apache.org/POM/4.0.0
   xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance
   xsi:schemaLocation=http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd>
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-parent</artifactId>
      <version>2.5.2</version>
      <relativePath /> <!-- lookup parent from repository -->
   </parent>
   <groupId>com..</groupId>
   <artifactId>extractTextFromMedia</artifactId>
   <version>0.0.1-SNAPSHOT</version>
   <name>extractTextFromMedia</name>
   <description>Project for extracting the text from media files</description>
   <properties>
      <java.version>11</java.version>
   </properties>
   <dependencies>
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-actuator</artifactId>
      </dependency>

      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-web</artifactId>
      </dependency>

      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-thymeleaf</artifactId>
      </dependency>

      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-configuration-processor</artifactId>
         <optional>true</optional>
      </dependency>

      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-validation</artifactId>
      </dependency>

      <dependency>
         <groupId>org.projectlombok</groupId>
         <artifactId>lombok</artifactId>
         <optional>true</optional>
      </dependency>
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-test</artifactId>
         <scope>test</scope>
      </dependency>

      <!-- video to audio -->
      <dependency>
         <groupId>ws.schild</groupId>
         <artifactId>jave-all-deps</artifactId>
         <version>3.2.0</version>
      </dependency>

      <!-- azure -->
      <dependency>
         <groupId>com.microsoft.cognitiveservices.speech</groupId>
         <artifactId>client-sdk</artifactId>
         <version>1.20.0</version>
      </dependency>

      <!-- sentiment analysis -->
      <!-- https://mvnrepository.com/artifact/com.azure/azure-ai-textanalytics -->
      <dependency>
         <groupId>com.azure</groupId>
         <artifactId>azure-ai-textanalytics</artifactId>
         <version>5.1.7</version>
      </dependency>

      <dependency>
         <groupId>com.squareup.okhttp3</groupId>
         <artifactId>okhttp</artifactId>
      </dependency>

      <dependency>
         <groupId>org.apache.commons</groupId>
         <artifactId>commons-lang3</artifactId>
      </dependency>


   </dependencies>

   <repositories>
      <repository>
         <id>maven-cognitiveservices-speech</id>
         <name>Microsoft Cognitive Services Speech Maven Repository</name>
         <url>https://csspeechstorage.blob.core.windows.net/maven/</url>
      </repository>
   </repositories>

   <build>
      <plugins>
         <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <configuration>
               <requiresUnpack>
                  <dependency>
                     <groupId>com.microsoft.cognitiveservices.speech</groupId>
                     <artifactId>client-sdk</artifactId>
                     <version>1.20.0</version>
                  </dependency>
               </requiresUnpack>
               <excludes>
                  <exclude>
                     <groupId>org.projectlombok</groupId>
                     <artifactId>lombok</artifactId>
                  </exclude>
               </excludes>
            </configuration>
         </plugin>
      </plugins>
   </build>

</project>
```
I run my program by building it into a fat .jar file with mvn clean package, transfer the jar to my VM and run it through a service there (with java -jar). 

I have installed the packages indicated here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7

I have also tried transferring the whole project folder in the VM and running it there, but I get the same error. I am unsure what to try next.

**Comment by jhakulin** [comment]
@floringolintchi Thanks for the report. java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory, is probably due to libMicrosoft.CognitiveServices.Speech.java.bindings.so does not get loaded for some reason.
Are you using Windows Subsystem for Linux (WSL) for CentOS7 ?

@BrianMouncer Would you take a look at this ?

**Comment by floringolintchi** [comment]
> @floringolintchi Thanks for the report. java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory, is probably due to libMicrosoft.CognitiveServices.Speech.java.bindings.so does not get loaded for some reason. Are you using Windows Subsystem for Linux (WSL) for CentOS7 ?

No, just a regular machine I ssh into. 

I've set a System.out.println(System.getProperty("java.library.path")); inside my endpoint to see if the program loads the libraries and you are right: /usr/local/lib64 is not set. I have tried setting it with -Djava.library.path, but it still doesn't seem to use them. Here is how the final command I've run looks like:

`sudo java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Djava.io.tmpdir=/export/home/fos/tmpDir -Djava.library.path=/usr/local/speech2text/speechSDK-1.20/ASSETS/linux-x64:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib:/usr/local/lib64:/usr/local/speech2text/speechSDK-1.20/ASSETS/centos7-x64 -jar extract-text-from-media-0.0.1-SNAPSHOT.jar
`
(also tried includint the speechSDK-1.20/ASSETS/centos7-x64 contents inside /usr/local/lib64)

What is weirder is that I've manage to run the sample code in this github without much problem yesterday on the same machine. Maybe this is related to spring boot somehow?

[link to stackoverflow q I've also opened](https://stackoverflow.com/questions/71827218/java-lang-unsatisfiedlinkerror-void-com-microsoft-cognitiveservices-speech-spe)

**Comment by pankopon** [comment]
@floringolintchi Please follow all the instructions in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7. You need to set **`LD_LIBRARY_PATH`** (or alternatively modify `/etc/ld.so.conf`) to point to `/usr/local/lib64` (or whereever the updated C++ runtime libraries are installed). This must be in effect either in the same console where the Java application is run, or as a system-wide default. so that newer C++ runtimes are found no matter where the application using the Speech SDK is launched from.

**Comment by floringolintchi** [comment]
> @floringolintchi Please follow all the instructions in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7. You need to set **`LD_LIBRARY_PATH`** (or alternatively modify `/etc/ld.so.conf`) to point to `/usr/local/lib64` (or whereever the updated C++ runtime libraries are installed). This must be in effect either in the same console where the Java application is run, or as a system-wide default. so that newer C++ runtimes are found no matter where the application using the Speech SDK is launched from.

I've tried that before and retried again now. I get the same stack trace from the OP. The application does grab the libraries however if they are set in $LD_LIBRARY_PATH.

**Comment by BrianMouncer** [comment]
@floringolintchi "I've tried setting LD_LIBRARY_PATH before and retried again now. I get the same stack trace from the OP. The application does grab the libraries without any more arguments in the command however if they are set in $LD_LIBRARY_PATH, it just still doesn't seem to use them, since it fails in the native setTempDirectory."

For the C+++ runtime so files, have you checked the order of the directories in the LD_LIBRARY_PATH.

For the TEMP directory, I what was the failure related to, access permissions, or with detecting to distro and unpacking the correct files for your system?

**Comment by pankopon** [comment]
@floringolintchi Can you try explicitly loading the SDK Java bindings library from the application code first, to see if it makes any difference:
```
try {
  System.loadLibrary("Microsoft.CognitiveServices.Speech.java.bindings");
  // log success
} catch (Exception e) {
  // log error
}
```

**Comment by pankopon** [comment]
Closing the item since an Azure service ticket was created instead (internal ref. 314142255). According to discussion between the customer and a support engineer, the actual application environment was a docker container based on Alpine Linux, which is not supported (see [Speech SDK system requirements on Linux](https://docs.microsoft.com/azure/cognitive-services/speech-service/speech-sdk?tabs=linux%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio#get-the-speech-sdk)). Information about recommended alternatives has been communicated. Please create a new issue if further support is needed.

**Comment by floringolintchi** [comment]
The environment was a centos 7 server. I'm not aware of any discussion between us and a support engineer. We've since switched to a windows server and finished working with this application for now, so I didn't have the time to retry all the steps. I can say from memory that manually loading the library in the program did not work. 

I will update this comment today with the result from checking your other suggestions if I get a chance, otherwise we can just leave it closed.
