### ISSUE TITLE
Error calling method CreateProgileAsync when implementing the Speech Verification

### ISSUE THREAD

**Issue by amaroRafael** [Azure-Samples/cognitive-services-speech-sdk#1513]
I have implemented Speech Verification where I followed the instruction from the document: [https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speaker-recognition?tabs=script&pivots=programming-language-csharp&WT.mc_id=Portal-Microsoft_Azure_Support](Speaker recognition)

This is my code:
`async void Enroll(VoiceProfileType profileType, Action<string> onEnrolling, Action<VoiceProfile> onEnrolled, Action<VoiceProfile, VoiceProfileEnrollmentCancellationDetails> onError)
{
    var config = SpeechConfig.FromSubscription("subscription_key", "region");

    using (var client = new VoiceProfileClient(config))
    using (var profile = await client.CreateProfileAsync(profileType, "en-us"))
    {
        var phraseResult = await client.GetActivationPhrasesAsync(profileType, "en-us");
        using (var audioInput = AudioConfig.FromDefaultMicrophoneInput())
        {
            Console.WriteLine($"Enrolling profile id {profile.Id}.");

            VoiceProfileEnrollmentResult result = null;
            while (result is null || result.RemainingEnrollmentsCount > 0)
            {
                Console.WriteLine($"Speak the passphrase, \"${phraseResult.Phrases[0]}\"");
                onEnrolling(phraseResult.Phrases[0]);
                result = await client.EnrollProfileAsync(profile, audioInput);
                Console.WriteLine($"Remaining enrollments needed: {result.RemainingEnrollmentsCount}");
            }

            if (result.Reason == ResultReason.EnrolledVoiceProfile)
            {
                await SpeakerVerify(config, profile, onEnrolling);
                onEnrolled(profile);
            }
            else if (result.Reason == ResultReason.Canceled)
            {
                var cancellation = VoiceProfileEnrollmentCancellationDetails.FromResult(result);
                Console.WriteLine($"CANCELED {profile.Id}: ErrorCode={cancellation.ErrorCode} ErrorDetails={cancellation.ErrorDetails}");
                onError(profile, cancellation);
            }
        }
    }
}`

When the method CreateProfileAsync was executing it threw an error
Exception with an error code: 0x1b (SPXERR_RUNTIME_ERROR)

Stack message:
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Speaker.VoiceProfileClient.<>c__DisplayClass5_0.<CreateProfileAsync>b__0(InteropSafeHandle h)
   at Microsoft.CognitiveServices.Speech.Speaker.VoiceProfileClient.<>c__DisplayClass13_0`1.<RunAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

The voice profile type I am passing is VoiceProfileType.TextIndependentVerification
I tried with different types, but I got the same error

I cannot figure out what I have been doing wrong.
Suppose anyone has this same error. Can you help me? please

**Comment by ralph-msft** [comment]
Thanks for trying the Cognitive Services Speech SDK.

Speaker recognition is in limited access review. If you haven't already, you'll need to request access using the [Azure Cognitive Services Speaker Recognition Limited Access Review](https://aka.ms/azure-speaker-recognition) form. You can also find that link on the [C# Quickstart page](https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speaker-recognition?tabs=script&pivots=programming-language-csharp).

The next version of the SDK will include error reporting that makes it easier to identify the cause of the errors. In the meantime, you can also enable logging to a file to make it easier to debug issues using [the instructions here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging).
