### ISSUE TITLE
Failed to initialize platform (azure-c-shared). Error: 2153

### ISSUE THREAD

**Issue by harlanhu** [Azure-Samples/cognitive-services-speech-sdk#1627]
Environment:
```
Linux version 4.18.0-80.7.2.el7.aarch64 (mockbuild@aarch64-01.bsys.centos.org) (gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC))

CentOS Linux release 7.6.1810 (AltArch)

openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)
```

I tried to use the Java Sdk for speech synthesis and encountered this problem at startup.
```java
Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1220)
	... 90 common frames omitted
Caused by: java.lang.IllegalArgumentException: Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
	at com.microsoft.cognitiveservices.speech.util.Contracts.throwIfFail(Unknown Source)
	at com.microsoft.cognitiveservices.speech.SpeechSynthesizer.<init>(Unknown Source)
	at com.youzidata.api.service.MicrosoftSpeechService.<clinit>(MicrosoftSpeechService.java:65)
	... 97 common frames omitted
```
What should I do about it ?

**Comment by glecaros** [comment]
Hi @harlanhu, the SDK does not currently support architectures other than x64 for CentOS 7 ([docs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7))
