### ISSUE TITLE
Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153

### ISSUE THREAD

**Issue by bmfire1** [Azure-Samples/cognitive-services-speech-sdk#1648]
erro info as:

Unhandled exception. System.AggregateException: One or more errors occurred. (Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153)
 ---> System.ApplicationException: Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.SpeechSynthesizer.FromConfig(SpeechConfig speechConfig)
   at Microsoft.CognitiveServices.Speech.SpeechSynthesizer..ctor(SpeechConfig speechConfig)
   at MicrosoftSpeechSDKSamples.SpeechSynthesisSamples.SynthesisToSpeakerAsync() in /home/ubuntu/newspace/unity_csharp/mstts/csharp/sharedcontent/console/speech_synthesis_samples.cs:line 24
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MicrosoftSpeechSDKSamples.Program.SpeechSynthesis() in /home/ubuntu/newspace/unity_csharp/mstts/csharp/sharedcontent/console/Program.cs:line 247
   at MicrosoftSpeechSDKSamples.Program.Main(String[] args) in /home/ubuntu/newspace/unity_csharp/mstts/csharp/sharedcontent/console/Program.cs:line 63
Aborted (core dumped)

env:
ubuntu 16.04
.net core 3.1

**Comment by pankopon** [comment]
Hi, you need Ubuntu 18.04 or newer. Please see the platform requirements:
https://docs.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=linux
