### ISSUE TITLE
UnsatisfiedLinkError com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory

### ISSUE THREAD

**Issue by 1893945** [Azure-Samples/cognitive-services-speech-sdk#1713]
**Describe the bug**
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V

**To Reproduce**
1. use IDEA run java samples code
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
SDK version 1.23.0

**Platform, Operating System, and Programming Language**
 - OS: win7
 - Hardware - x64
 - Programming language: Java

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
	at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
	at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(Unknown Source)
	at com.microsoft.cognitiveservices.speech.samples.console.SpeechSynthesisSamples.synthesisToWaveFileAsync(SpeechSynthesisSamples.java:232)
	at com.microsoft.cognitiveservices.speech.samples.console.Main.main(Main.java:134)

**Comment by 1893945** [comment]
jdk1.8.0_121

**Comment by ralph-msft** [comment]
Unfortunately, the SDK does not support Windows 7. You'll need to be using Windows 10 (64 bit) or newer.

Please refer to the documentation provided here for additional information on other pre-requisites:
https://learn.microsoft.com/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-java
