### ISSUE TITLE
Pronunciation Assessment using Python Speech SDK

### ISSUE THREAD

**Issue by AdityaYadavalli1** [Azure-Samples/cognitive-services-speech-sdk#1763]
**Describe the bug**
KeyError when using Pronunciation Assessment feature in Python Speech SDK

**To Reproduce**
```python3
import azure.cognitiveservices.speech as speechsdk
import json

SUB_KEY="" # replace this with the subscription key
REG="" # replace this with the region key

def recognize_from_file(wav_file, pronunciation_assessment_config):
    speech_config = speechsdk.SpeechConfig(subscription=SUB_KEY, region=REG)
    speech_config.speech_recognition_language="en-US"

    audio_config = speechsdk.audio.AudioConfig(filename=wav_file)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config)

    pronunciation_assessment_config.apply_to(speech_recognizer)
    speech_recognition_result = speech_recognizer.recognize_once()
    pronunciation_assessment_result = speechsdk.PronunciationAssessmentResult(speech_recognition_result)
    pronunciation_assessment_result_json = speech_recognition_result.properties.get(speechsdk.PropertyId.SpeechServiceResponse_JsonResult)
    return pronunciation_assessment_result_json

pronunciation_assessment_config = speechsdk.PronunciationAssessmentConfig(json_string="{\"referenceText\":\"good morning.\",\"gradingSystem\":\"HundredMark\",\"granularity\":\"FullText\"}")
wav_file = "" # path to a wav file
pron_assessment = recognize_from_file(wav_file, pronunciation_assessment_config)
```

**Expected behavior**
code runs without error and the variable `pron_assessment` has the json containing the pronunciation assessment scores for the corresponding reference text and wav file.

**Version of the Cognitive Services Speech SDK**
1.24.2

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Hardware - x64
 - Programming language: Python

**Additional context**
 - Stack Trace:
 ```
Traceback (most recent call last):
  File "pron_assess.py", line 24, in <module>
    pron_assessment = recognize_from_file(wav_file, pronunciation_assessment_config)
  File "pron_assess.py", line 18, in recognize_from_file
    pronunciation_assessment_result = speechsdk.PronunciationAssessmentResult(speech_recognition_result)
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/cognitiveservices/speech/speech.py", line 3111, in __init__
    self._words = [PronunciationAssessmentWordResult(w) for w in nb['Words']]
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/cognitiveservices/speech/speech.py", line 3111, in <listcomp>
    self._words = [PronunciationAssessmentWordResult(w) for w in nb['Words']]
  File "/home/azureuser/.local/lib/python3.8/site-packages/azure/cognitiveservices/speech/speech.py", line 3042, in __init__
    self._accuracy_score = _json['PronunciationAssessment'].get('AccuracyScore', 0)
KeyError: 'PronunciationAssessment'
```

**Comment by pankopon** [comment]
@yulin-li Please check.

**Comment by yulin-li** [comment]
@AdityaYadavalli1 thanks for using Azure pronunciation assessment and reporting this issue, I will check.

**Comment by dargilco** [comment]
@yulin-li confirming that I see the same thing. If take the above code, but with:
        pronunciation_assessment_config = speechsdk.PronunciationAssessmentConfig(
            reference_text="good-morning",
            grading_system=speechsdk.PronunciationAssessmentGradingSystem.HundredMark,
            granularity=speechsdk.PronunciationAssessmentGranularity.FullText)
it fails with the error above.
If I true to use granularity Phoneme or Word it works fine.

**Comment by dargilco** [comment]
@AdityaYadavalli1 I will fix this bug in the SDK. Thank you for pointing this out. The fix will be available in the next released version expected around end of January 2023. Meanwhile please use speechsdk.PronunciationAssessmentGranularity.Word and simply ignore the word-level PronunciationAssessment results in the JSON if you are only interested in full-sentence results.

**Comment by AdityaYadavalli1** [comment]
Thank you so much @dargilco for the workaround! Looking forward to the fix.

**Comment by dargilco** [comment]
@AdityaYadavalli1 the fix is in code review now. I will close this issue. The SDK [release notes](https://learn.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk) of the next version (1.25) will mention a fix for this GitHub issue.
