### ISSUE TITLE
Failed to initialize platform (azure-c-shared). Error: 2153

### ISSUE THREAD

**Issue by adadot** [Azure-Samples/cognitive-services-speech-sdk#1810]
We probably got something wrong but we can't start the demo synthesis program on Ubuntu 22.04
```
uname -a
Linux pop-os 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux
```
The  error is down in share libraries somewhere:
```
Traceback (most recent call last):
  File "/home/ric/Desktop/chatgpt_siri/speech_synthesis.py", line 11, in <module>
    speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)
  File "/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/speech.py", line 2108, in __init__
    _call_hr_fn(fn=_sdk_lib.synthesizer_create_speech_synthesizer_from_config, *[
  File "/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/interop.py", line 62, in _call_hr_fn
    _raise_if_failed(hr)
  File "/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/interop.py", line 55, in _raise_if_failed
    __try_get_error(_spx_handle(hr))
  File "/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/interop.py", line 50, in __try_get_error
    raise RuntimeError(message)
RuntimeError: Exception with error code: 
[CALL STACK BEGIN]

/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b9787) [0x7fefe35b9787]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1dd4b1) [0x7fefe35dd4b1]
/lib/x86_64-linux-gnu/libc.so.6(+0x99f68) [0x7fefe4e99f68]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1de66e) [0x7fefe35de66e]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a7399) [0x7fefe35a7399]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a5877) [0x7fefe35a5877]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c0099) [0x7fefe35c0099]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d832a) [0x7fefe35d832a]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x17ff00) [0x7fefe357ff00]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xe087d) [0x7fefe34e087d]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c0099) [0x7fefe35c0099]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x177dd3) [0x7fefe3577dd3]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1eb0b5) [0x7fefe35eb0b5]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(synthesizer_create_speech_synthesizer_from_config+0xf3) [0x7fefe34c5c02]
/lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7fefe5032e2e]
/lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7fefe502f493]
/usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xa451) [0x7fefe4dc3451]
[CALL STACK END]

Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153
```
And our little test code for completeness
```
# This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
speech_config = speechsdk.SpeechConfig(subscription=os.environ.get('SPEECH_KEY'), region=os.environ.get('SPEECH_REGION'))
audio_config = speechsdk.audio.AudioOutputConfig(use_default_speaker=True)

# The language of the voice that speaks.
speech_config.speech_synthesis_voice_name='en-US-JennyNeural'

speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config, audio_config=audio_config)

# Get text from the console and synthesize to the default speaker.
print("Enter some text that you want to speak >")
text = input()

speech_synthesis_result = speech_synthesizer.speak_text_async(text).get()

if speech_synthesis_result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
    print("Speech synthesized for text [{}]".format(text))
elif speech_synthesis_result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = speech_synthesis_result.cancellation_details
    print("Speech synthesis canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        if cancellation_details.error_details:
            print("Error details: {}".format(cancellation_details.error_details))
            print("Did you set the speech resource key and region values?")
```
Thanks

**Comment by ralph-msft** [comment]
Could you please enable the SDK logs and share those when reproducing the issue above? You can find instructions on how to do this here:
https://learn.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by adadot** [comment]
Looks like it does not like Ubuntu 22.04 libssl:

```
[99512]: 7ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:95 Created 'CSpxThreadService' as '303073113'
[99512]: 7ms SPX_DBG_TRACE_VERBOSE:  codec_adapter.cpp:28 CSpxCodecAdapter
[99512]: 7ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:95 Created 'CSpxCodecAdapter' as '199052375'
[99512]: 7ms SPX_DBG_TRACE_SCOPE_ENTER:  codec_adapter.cpp:43 Open
[99512]: 10ms SPX_TRACE_VERBOSE:  dynamic_module.cpp:52 dlopen('libMicrosoft.CognitiveServices.Speech.core.so') returned non-NULL
[99512]: 11ms SPX_TRACE_VERBOSE:  dynamic_module.cpp:58 dlsym('GetModuleObject') returned non-NULL
[99512]: 11ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:95 Created 'CSpxBlockingReadWriteRingBuffer' as '956428994'
[99512]: 13ms SPX_DBG_TRACE_SCOPE_EXIT:  codec_adapter.cpp:43 Open
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  codec_adapter.cpp:33 ~CSpxCodecAdapter
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  named_properties.h:476 ISpxPropertyBagImpl::SetStringValue: this=0x0x0055ac64fa9018; name='CodecAdapterAvailable'; value='true'
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  usp_tts_engine_adapter.cpp:48 CSpxUspTtsEngineAdapter
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  resource_manager.cpp:95 Created 'CSpxUspTtsEngineAdapter' as '919101823'
[99512]: 13ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  shim_openssl.c:51 libssl could not be loaded
[99512]: 13ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2152 Could not load libssl
[99512]: 13ms SPX_TRACE_ERROR:  exception.cpp:135 About to throw Runtime error: Failed to initialize platform (azure-c-shared). Error: 2153 
[CALL STACK BEGIN]

/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b9787) [0x7f09815b9787]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1dd4b1) [0x7f09815dd4b1]
/lib/x86_64-linux-gnu/libc.so.6(+0x99f68) [0x7f0982e99f68]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1de66e) [0x7f09815de66e]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a7399) [0x7f09815a7399]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1a5877) [0x7f09815a5877]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c0099) [0x7f09815c0099]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d832a) [0x7f09815d832a]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x17ff00) [0x7f098157ff00]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0xe087d) [0x7f09814e087d]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1c0099) [0x7f09815c0099]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x177dd3) [0x7f0981577dd3]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1eb0b5) [0x7f09815eb0b5]
/home/ric/.cache/pypoetry/virtualenvs/chatgpt-siri-7TtG-LRn-py3.10/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(synthesizer_create_speech_synthesizer_from_config+0xf3) [0x7f09814c5c02]
/lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e) [0x7f0983050e2e]
/lib/x86_64-linux-gnu/libffi.so.8(+0x4493) [0x7f098304d493]
/usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xa451) [0x7f0983073451]
[CALL STACK END]


[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  usp_tts_engine_adapter.cpp:53 ~CSpxUspTtsEngineAdapter: this=0x0x55ac6507ed00
[99512]: 13ms SPX_DBG_TRACE_SCOPE_ENTER:  synthesizer.cpp:41 ~CSpxSynthesizer
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:78 SpxTerm: ptr=0x0x55ac64f862f8
[99512]: 13ms SPX_DBG_TRACE_SCOPE_ENTER:  thread_service.cpp:40 Term
[99512]: 13ms SPX_DBG_TRACE_SCOPE_EXIT:  thread_service.cpp:40 Term
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:78 SpxTerm: ptr=0x0x55ac64fa3ff8
[99512]: 13ms SPX_DBG_TRACE_SCOPE_EXIT:  synthesizer.cpp:41 ~CSpxSynthesizer
[99512]: 13ms SPX_DBG_TRACE_SCOPE_ENTER:  thread_service.cpp:40 Term
[99512]: 13ms SPX_DBG_TRACE_SCOPE_EXIT:  thread_service.cpp:40 Term
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:108 CSpxHandleTable::TrackHandle p=0x0x55ac650da790
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:118 CSpxHandleTable::TrackHandle class=ExceptionWithCallStack, h=0x0x55ac650da790, p=0x0x55ac650da790, tot=1
[99512]: 13ms SPX_RETURN_ON_FAIL:  speechapi_c_factory.cpp:490 hr = 0x55ac650da790
[99512]: 13ms SPX_DBG_TRACE_SCOPE_EXIT:  speechapi_c_factory.cpp:480 synthesizer_create_speech_synthesizer_from_config
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:177 CSpxHandleTable::StopTracking(h) h=0x0x55ac650da790
[99512]: 13ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:192 CSpxHandleTable::StopTracking(h) class=ExceptionWithCallStack, h=0x0x55ac650da790, p=0x0x55ac650da790, tot=0
[99512]: 15ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:177 CSpxHandleTable::StopTracking(h) h=0x0x55ac64f8aa08
[99512]: 15ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:192 CSpxHandleTable::StopTracking(h) class=ISpxSpeechConfig, h=0x0x55ac64f8aa08, p=0x0x55ac64f8aa08, tot=0
[99512]: 15ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:177 CSpxHandleTable::StopTracking(h) h=0x0x55ac64f8a9a8
[99512]: 15ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:192 CSpxHandleTable::StopTracking(h) class=ISpxNamedProperties, h=0x0x55ac64f8a9a8, p=0x0x55ac64f8a9a8, tot=0
[99512]: 15ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:177 CSpxHandleTable::StopTracking(h) h=0x0x55ac64e83af0
[99512]: 15ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:192 CSpxHandleTable::StopTracking(h) class=ISpxAudioConfig, h=0x0x55ac64e83af0, p=0x0x55ac64e83af0, tot=1
[99512]: 16ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:177 CSpxHandleTable::StopTracking(h) h=0x0x55ac64e8d650
[99512]: 16ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:192 CSpxHandleTable::StopTracking(h) class=ISpxAudioConfig, h=0x0x55ac64e8d650, p=0x0x55ac64e8d650, tot=0
[99512]: 17ms SPX_DBG_TRACE_FUNCTION:  memory_logger.cpp:127 Exit
[99512]: 17ms SPX_DBG_TRACE_FUNCTION:  resource_manager.cpp:76 ~CSpxResourceManager
```

**Comment by ralph-msft** [comment]
Thank you for reporting this issue. Ubuntu 22.04 moved to OpenSSL version 3. The Cognitive Services Speech SDK has not been updated to support OpenSSL 3 and instead is still using OpenSSL 1.1.1.

We have labeled the issue as 'accepted' here and are now also tracking a fix for this in on our backlog (# 4471701). We will respond here once we have an update.

In the meantime, you _**may**_ be able to temporarily work around this by manually installing the OpenSSL 1.1.1 packages. However some issues to keep in mind:
- We have not tested if this causes conflicts with other packages or building other packages. Please proceed at your own risk
- You will need to manually ensure that you are using the latest OpenSSL 1.1.1 version yourself to avoid any potential security issues
```
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
```

**Comment by gameveloster** [comment]
After applying your temp fix, how do we revert OpenSSL v1.1.1 back to v3 in the efuture?

Where can we view the backlog ticket # 4471701?

**Comment by TheBicPen** [comment]
Note: OpenSSL 1.1.1 support will end in September 2023 so hopefully the SDK will be updated before then.
https://www.openssl.org/source/

**Comment by gameveloster** [comment]
@ralph-msft The url in your `wget` command does not work... any updated url?

```
# wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
--2023-04-11 03:55:28--  http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
Resolving archive.ubuntu.com (archive.ubuntu.com)... 2620:2d:4000:1::16, 2001:67c:1562::15, 2001:67c:1562::18, ...
Connecting to archive.ubuntu.com (archive.ubuntu.com)|2620:2d:4000:1::16|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-11 03:55:28 ERROR 404: Not Found.
```

**Comment by jbennink** [comment]
@gameveloster an url that did work was: http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb with that the speech sdk did run.

**Comment by crankyfish** [comment]
It's not just an Ununtu issue - RHEL 9 based distros (such as Rocky 9) will have the problem too.  Under Rocky 9, I was able to use the workaround suggested, but instead of overwriting the system openssl package with an earlier version, I downloaded the source and built it in a separate directory.  I had to put a link to the system cert.pem in the openssl 1.1.1 cert directory, and set the LD_LIBRARY_PATH to the 1.1.1 lib directory prior to running the speech stuff, but it works fine.  Yay!

I just didn't like the thought of overwriting a system package and breaking something in a way that might not be obvious.

**Comment by adam-kiss-sg** [comment]
@ralph-msft Hi! Is there any update on # 4471701?

**Comment by tushroy** [comment]
I have made my own docker base image related to cognitive-services-speech-sdk 
and able to run on top of it.
find it here. https://github.com/tushroy/az-speech-dotnet/blob/main/Dockerfile
or the docker base image here: 
https://github.com/tushroy/az-speech-dotnet/pkgs/container/az-speech-dotnet

**Comment by jjanczur** [comment]
Is there any update? Azure Cognitive services using OpenSSL 1.1.1 which EOL is in 2023 is not the best news and the nasty workaround with installing it separately is not what I'd expect from Microsoft!

**Comment by Baklap4** [comment]
Linking issue: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2048 since all other issues are closed.

**Comment by waveBoom** [comment]
python temporary solution : https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2204#issuecomment-2075395036
