### ISSUE TITLE
SPXERR_GSTREAMER_NOT_FOUND_ERROR, Python, Windows 11

### ISSUE THREAD

**Issue by ToadyWario** [Azure-Samples/cognitive-services-speech-sdk#1837]
I'm having an issue with running azure-cognitiveservices-speech **python** SDK which uses **GStreamer**. I followed the instruction [Quickstart: Create captions with speech to text](https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/captioning-quickstart?tabs=windows%2Cterminal&pivots=programming-language-python) and got the following error: 

```Traceback (most recent call last):
  File "C:\Users\z\Desktop\cognitive-services-speech-sdk-master\scenarios\python\console\captioning\captioning.py", line 355, in <module>
    speech_recognizer_data = captioning.speech_recognizer_from_user_config()
  File "C:\Users\z\Desktop\cognitive-services-speech-sdk-master\scenarios\python\console\captioning\captioning.py", line 263, in speech_recognizer_from_user_config
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config_data["audio_config"])
  File "C:\Users\z\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\azure\cognitiveservices\speech\speech.py", line 1004, in __init__
    _call_hr_fn(
    - recognizer_create_speech_recognizer_from_config    - ffi_prep_go_closure
    - ffi_call_go
    - ffi_call    - 00007FFB60E62C35 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FFB60E629B7 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FFB60E62628 (SymFromAddr() error: Attempt to access invalid address.)    - PyObject_Call
    - PyEval_EvalFrameDefault
    - PyFunction_Vectorcall

[CALL STACK END]

Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
```

   

When running gst-inspect-1.0.exe --version I can see that GStreamer is available:

```
gst-inspect-1.0 version 1.18.3                                                                                                                                  
GStreamer 1.18.3
Unknown package origin
```

I am using azure-cognitiveservices-speech 1.25.0, Windows 11, Python 3.10.

I was trying to use older and latest version of SDK but I'm still getting the same error.

**Comment by pankopon** [comment]
Hi, please check these similar issues in the past for configuration notes:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1138
https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1788

**Comment by pankopon** [comment]
Closed as a duplicate, please open a new issue if more support is needed.
