### ISSUE TITLE
Run python captioning test

### ISSUE THREAD

**Issue by NarsuAltan** [Azure-Samples/cognitive-services-speech-sdk#1859]
**Describe the bug**
Run the given captioning test.
python captioning.py --input file.wav --format any --output caption.output.txt --srt --realTime --threshold 5 --delay 0 --profanity mask --phrases "Contoso;Jessie;Rehaan" 

**To Reproduce**
1. ...
2. ...

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: [Windows
 - Hardware - x64, x86, ARM, ...
 - Programming language: Python 3.10.10
 - console

**Additional context**
........................... <azure.cognitiveservices.speech.SpeechConfig object at 0x0000024C45E34820>
........................... <azure.cognitiveservices.speech.audio.AudioConfig object at 0x0000024C45E346D0>
Traceback (most recent call last):
  File "C:\Users\ybpcn\Downloads\cognitive-services-speech-sdk-master\scenarios\python\console\captioning\captioning.py", line 364, in <module>
    speech_recognizer_data = captioning.speech_recognizer_from_user_config()
  File "C:\Users\ybpcn\Downloads\cognitive-services-speech-sdk-master\scenarios\python\console\captioning\captioning.py", line 271, in speech_recognizer_from_user_config
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, audio_config=audio_config_data["audio_config"])
  File "C:\Users\ybpcn\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 1004, in __init__
    _call_hr_fn(
  File "C:\Users\ybpcn\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cognitiveservices\speech\interop.py", line 62, in _call_hr_fn
    _raise_if_failed(hr)
  File "C:\Users\ybpcn\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cognitiveservices\speech\interop.py", line 55, in _raise_if_failed
    __try_get_error(_spx_handle(hr))
  File "C:\Users\ybpcn\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cognitiveservices\speech\interop.py", line 50, in __try_get_error
    raise RuntimeError(message)
RuntimeError: Exception with error code:
[CALL STACK BEGIN]

    > pal_string_to_wstring
    - pal_string_to_wstring
    - pal_string_to_wstring
    - pal_string_to_wstring
    - pal_string_to_wstring
    - recognizer_create_speech_recognizer_from_config
    - recognizer_create_speech_recognizer_from_config
    - ffi_prep_go_closure
    - ffi_call_go
    - ffi_call
    - 00007FF9BE052C35 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF9BE0529B7 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FF9BE052628 (SymFromAddr() error: Attempt to access invalid address.)
    - PyObject_Call
    - PyEval_EvalFrameDefault
    - PyFunction_Vectorcall

[CALL STACK END]

Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)

**Comment by goergenj** [comment]
Please verify you have installed gstreamer correctly and added the correct environment variables for your speech resource.

See https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/captioning-quickstart?tabs=windows%2Cterminal&pivots=programming-language-python

**Comment by NarsuAltan** [comment]
Thank you. I didn't set up gstreamer. It's working great
