### ISSUE TITLE
"Microsoft.CognitiveServices.Speech.core.dll" not found

### ISSUE THREAD

**Issue by Boboswitch** [Azure-Samples/cognitive-services-speech-sdk#1897]
Hi, I am using Azure Cognitive Services Speech to do a speech recognition project. However, I keep running into this error when running my python script in Visual Studio Code. I am using python 3.11.2 and have installed my packages in a virtual environment. I have tried to run the script on 3 different computers and run into the same issue. Error code below. Thanks in advance for any help:)

Traceback (most recent call last):
  File "C:\Users\Cortana\Documents\DevelopersSpace\V.3\CortanaAIv3.py", line 4, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\__init__.py", line 8, in <module>
    from .speech import *
  File "c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\speech.py", line 13, in <module>
    from .interop import (
    _sdk_lib = load_library.LoadLibrary(lib_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 454, in LoadLibrary
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\Microsoft.CognitiveServices.Speech.core.dll' (or one of its dependencies). Try using the full path with constructor syntax.
(Cortana) PS C:\Users\Cortana\Documents\DevelopersSpace\V.3> pip uninstall SpeechRecognition
WARNING: Skipping SpeechRecognition as it is not installed.
(Cortana) PS C:\Users\Cortana\Documents\DevelopersSpace\V.3>  c:; cd 'c:\Users\Cortana\Documents\DevelopersSpace\V.3'; & 'c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Scripts\python.exe' 'c:\Users\Cortana\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '62205' '--' 'C:\Users\Cortana\Documents\DevelopersSpace\V.3\tester.py'
Traceback (most recent call last):
  File "C:\Users\Cortana\Documents\DevelopersSpace\V.3\tester.py", line 1, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\__init__.py", line 8, in <module>
    from .speech import *
  File "c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\speech.py", line 13, in <module>
    from .interop import (
  File "c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\interop.py", line 20, in <module>
    _sdk_lib = load_library.LoadLibrary(lib_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'c:\Users\Cortana\Documents\DevelopersSpace\V.3\Cortana\Lib\site-packages\azure\cognitiveservices\speech\Microsoft.CognitiveServices.Speech.core.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by M-Hietala** [comment]
I was successfully able to run a Speech SDK sample under Visual Studio Code with the SDK installed in virtual environment. Could you make sure you have installed Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads as the Speech SDK depends on it. If that does not help, could you provide detailed steps how you setup your environment so we can try to reproduce following them. Also, which version of Speech SDK are you using?

**Comment by Boboswitch** [comment]
Thank you so much for your help. I had already installed Visual C++ for my system, but it wasn't working. I uninstalled and reinstalled Visual C++, and it all of a sudden started working. Just for reference I was working on a 2009 Mac Mini running windows as the only operating system on the machine. 

Again, thank you so much for your help. It is greatly appreciated!

**Comment by Starr79** [comment]
✨️
