### ISSUE TITLE
Microsoft.CognitiveServices.Speech.core.dll not found, NuGet errors

### ISSUE THREAD

**Issue by jtsoftware** [Azure-Samples/cognitive-services-speech-sdk#1907]
**Describe the bug**
Running new code using the text to speech for the first time. In calling the SpeechConfig.FromSubscription function I get the exception:

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=Microsoft.CognitiveServices.Speech.csharp
  StackTrace:
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at JTLanguageModelsWindows.Media.TextToSpeechPlatform.<GetMicrosoftVoiceList>d__38.MoveNext() in C:\JTLanguage\JTLanguageModelsWindows\Media\TextToSpeechPlatform.cs:line 832

However, I failed to notice that there were some NuGet errors when I installed the Microsoft.CognitiveServices.Speech package via NuGet. See the errors below.

**To Reproduce**
1. Create new .Net console project, .Net 4.7.2 (I called it JTExp).
2. Open Manage NuGet Packages for Solution and add Microsoft.CognitiveServices.Speech.
3. See the NuGet errors:

Successfully installed 'Microsoft.CognitiveServices.Speech 1.27.0' to JTExp
Failed to update binding redirects for JTExp\JTExp.csproj : Exception has been thrown by the target of an invocation.

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#
 - Browser Edge

**Additional context**

I'm running an AST.NET web app using .NET Framework 4.7.2.

I installed the Microsoft.CognitiveServices.Speech 1.27.0 via Manage NuGet Packages for Solution in a freshly updated Visual Studio 2022 (17.5.3), however, I failed to notice there were some error messages:

Successfully installed 'Microsoft.CognitiveServices.Speech 1.27.0' to JTLanguageModelsWindows
Failed to update binding redirects for JTLanguageModelsWindows\JTLanguageModelsWindows.csproj : Exception has been thrown by the target of an invocation.
Executing nuget actions took 2.05 sec
Package 'Microsoft.CognitiveServices.Speech.1.27.0' already exists in folder 'C:\JTLanguage\packages'
Added package 'Microsoft.CognitiveServices.Speech.1.27.0' to 'packages.config'
Successfully installed 'Microsoft.CognitiveServices.Speech 1.27.0' to JTLanguageWeb
Failed to update binding redirects for JTLanguageWeb\JTLanguageWeb.csproj : Exception has been thrown by the target of an invocation.
Executing nuget actions took 1.37 sec
Package 'Microsoft.CognitiveServices.Speech.1.27.0' already exists in folder 'C:\JTLanguage\packages'
Added package 'Microsoft.CognitiveServices.Speech.1.27.0' to 'packages.config'
Successfully installed 'Microsoft.CognitiveServices.Speech 1.27.0' to JTLanguageWorker
Failed to update binding redirects for JTLanguageTools\JTLanguageWorker\JTLanguageWorker.csproj : Exception has been thrown by the target of an invocation.

These are the messages from my repo case:

Attempting to gather dependency information for package 'Microsoft.CognitiveServices.Speech.1.27.0' with respect to project 'JTExp', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 347 ms
Attempting to resolve dependencies for package 'Microsoft.CognitiveServices.Speech.1.27.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.CognitiveServices.Speech.1.27.0'
Resolved actions to install package 'Microsoft.CognitiveServices.Speech.1.27.0'
Package 'Microsoft.CognitiveServices.Speech.1.27.0' already exists in folder 'C:\JTLanguage\packages'
Added package 'Microsoft.CognitiveServices.Speech.1.27.0' to 'packages.config'
Successfully installed 'Microsoft.CognitiveServices.Speech 1.27.0' to JTExp
Failed to update binding redirects for JTExp\JTExp.csproj : Exception has been thrown by the target of an invocation.
Executing nuget actions took 897 ms
Time Elapsed: 00:00:01.2527044
========== Finished ==========

**Comment by rhurey** [comment]
I was able to get this to reproduce for an ASP.Net framework based web app. 

Talking to a colleague, there had been another report of this issue, that customer worked around it by switching to a dotnet core based app.

Looking at the deployed webapp in Azure, the native dll's that the SDK depends on aren't being deployed into the bin folder, not sure why they aren't.

**Comment by rhurey** [comment]
Ok, I managed to get the Speech SDK to load in a .Net Framework based web app.

The steps...
ANY CPU didn't work, as it builds for the current machine, and not the target machine.
I selected a x86 build (my Azure web app was 32 bit windows) and built it locally.
Then in the webapp project's property page under Publish there is an option to deploy all files in the project folder and that deployed the core dll to the site.

**Comment by glecaros** [comment]
hi @jtsoftware, were you able to resolve your issue with @rhurey's suggestion?

**Comment by jtsoftware** [comment]
Sorry, I've been on vacation out of the country the last two weeks.

No, I haven't been able to resolve this. I tried creating a web app with ASP.Net 4.7.2 with MVC, and added x86 and x64 configurations, but I get a build error:

1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'WebApplication1.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x86'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.

Apparently, adding that configuration didn't add the necessary stuff to the project file.  How did you do it?

I get the same kind of error if I try it in my main solution.

The problem is that I have a 10-year old legacy solution with 22 projects totaling over ~1 million lines of code, so I'm kind of uncomfortable messing around with the core configuration. Converting to dotnet core would probably kill the project with the effort needed to convert to something newer. A bit after I originally created the project, I tried switching to the new core libraries, but it was missing some key functionality I used, so I stayed with the .Net framework.

Rather than me trying to work around the problem, can you fix the problems that are keeping me from being able to use it? or give me a simpler solution such as just copying some libraries? Otherwise, I may have to stick with using Google Text-to-Speech, which works fine, though I really would like to use the Microsoft voices. This is for a language learning platform, so have good speech is important.

**Comment by jtsoftware** [comment]
I tried the nuGet install again, and it worked, the only difference being that I ran it in a Visual Studio not as Administrator. (You can only debug web apps as an Administrator). I don't see the .core library in bin\Debug, but I am able to call functions without getting the Unable to load DLL message. I haven't got the code fully working, but I can generate a .wav file, so it looks like the problem is not fatal. Should I close this, or does it need more research?

**Comment by jtsoftware** [comment]
Actually, I forgot that I added the core DLL path to the PATH variable, which is why it works for me. i.e.:

C:\JTLanguage\packages\Microsoft.CognitiveServices.Speech.1.27.0\runtimes\win-x64\native;

So a fix for nuGet is still probably needed.

**Comment by jtsoftware** [comment]
I have a second machine and installed the nuGet package and set the path like above, but it still can't find the DLL. If I copy the DLLs manually to the web app bin directory, I get a System.ApplicationError exception with error code 5. Any ideas?

**Comment by rhurey** [comment]
Is the WebApp running x64?

The default for the WebApp was x86 when I was looking at this.

The key takeaway from when I'd gotten a successful run was getting the correct native binaries in the runtime directory, and then having them published to the cloud.

I'd set my local build to x86 to achieve the first part, and then there was a project setting that published all the files in the target directory to the cloud, and not just ones that showed up as a managed reference.

**Comment by jtsoftware** [comment]
I got the text to speech working. I didn't have the license files in place. Does this account for error 5? Or could there be something more random going on that's unrelated? Because the runtime libraries are not in the bin directory of the other machine the worked first.

I'm still using Any CPU, as I couldn't get either x64 or x86 to build.

**Comment by jhakulin** [comment]
This seems like related issue and there is workaround for .NET framework
https://stackoverflow.com/questions/75616169/unable-to-load-dll-microsoft-cognitiveservices-speech-core-dll-could-not-be-f/75623332#75623332
We would need to update the NuGet to automatically to deploy all binaries.

**Comment by jhakulin** [comment]
Closing the issue as there has been workarounds provided, we will plan the support to official Nuget.
