### ISSUE TITLE
0x38 (SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND) in .net 7.0 

### ISSUE THREAD

**Issue by sergiu-gheorghe** [Azure-Samples/cognitive-services-speech-sdk#1959]
I'm getting the following exception:

```
System.ApplicationException: Exception with an error code: 0x38 (SPXERR_AUDIO_SYS_LIBRARY_NOT_FOUND)
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.SpeechSynthesizer.FromConfig(SpeechConfig speechConfig)
   at Microsoft.CognitiveServices.Speech.SpeechSynthesizer..ctor(SpeechConfig speechConfig)
```
when using azure text to speech in .net 7.0 console application that is deployed in kubernetes using debian 11.6 version.

Note that the application is running without any exception locally only getting this exception when deployed to kubernetes.

I have tried to add this command to docker file
`RUN apt-get update && apt-get install -y build-essential libssl-dev ca-certificates libasound2 wget` as stated here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-csharp&tabs=linux%2Cdebian%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi: but it didn't help

**Comment by sergiu-gheorghe** [comment]
Found the problem on our side, the command
RUN apt-get update && apt-get install -y build-essential libssl-dev ca-certificates libasound2 wget was not run properly from dockerfile and it wasn't installing the libasound2
