### ISSUE TITLE
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

### ISSUE THREAD

**Issue by frank-vanderhulst** [Azure-Samples/cognitive-services-speech-sdk#1973]
**Describe the bug**
Building with VS2019 results in an exception at runtime
**To Reproduce**
1. Build supplied code with VS2019
2. Run the IIS website
3. Call the TextToSpeechService constructor.

**Expected behavior**
If built with VS2022, no exception is raised and everything works as expected.

**Version of the Cognitive Services Speech SDK**
1.28

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: C#
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=Microsoft.CognitiveServices.Speech.csharp
  StackTrace:
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at Admin.AppCode.Services.TextToSpeechService..ctor() in C:\Users\frank.vanderhulst\source\repos\stk-core\Admin\Admin\AppCode\Services\TextToSpeechService.cs:line 34
   at Admin.Controllers.DoTController..ctor(BaseControllerDependencies depts, ISpectreService spectreService, ISmartrakContext smartrakContext, IRemoteTimeService remoteTimeService) in C:\Users\frank.vanderhulst\source\repos\stk-core\Admin\Admin\Controllers\DoTController.cs:line 24
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
   at Ninject.KernelBase.Resolve(IRequest request)
   at Ninject.Extensions.ContextPreservation.ContextPreservingResolutionRoot.Resolve(IRequest request)
   at Ninject.Web.Mvc.NinjectDependencyResolver.GetService(Type serviceType)
   at System.Web.Mvc.DefaultControllerFactory.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType)
`using System;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;
using System.IO;
using Admin.Util;

namespace Admin.AppCode.Services
{
	public interface ITextToSpeechService
	{
		/// <summary>
		/// Convert a given string to speech
		/// </summary>
		/// <param name="text">The text to convert</param>
		/// <returns>SpeechSynthesisResult containing the data bytes (AudioData) and duration</returns>
		SpeechSynthesisResult Convert(string text);
	}

	public class TextToSpeechService : ITextToSpeechService
	{
		private readonly SpeechSynthesizer _speechSynthesizer;
		private PushAudioOutputMemoryStreamCallback _callback;

		public TextToSpeechService()
		{
			/*
			 	Requires VS2022. If this is built with VS2019, at runtime it results in an exception from Microsoft.CognitiveServices.Speech.csharp
				{"An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"}

					at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
					at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
			 */
			SpeechSynthesisOutputFormat format = SpeechSynthesisOutputFormat.Audio16Khz64KBitRateMonoMp3;
			var speechConfig = SpeechConfig.FromSubscription(Constants.TextToSpeech.CognitiveServicesKey, Constants.TextToSpeech.CognitiveServicesRegion);
			speechConfig.SpeechSynthesisVoiceName = Constants.TextToSpeech.CognitiveServicesVoice;
			speechConfig.SetSpeechSynthesisOutputFormat(format);
			_callback = new PushAudioOutputMemoryStreamCallback();
			var audioConfig = AudioConfig.FromStreamOutput(_callback);
			_speechSynthesizer = new SpeechSynthesizer(speechConfig, audioConfig);
		}

		public SpeechSynthesisResult Convert(string text)
		{
			if (string.IsNullOrWhiteSpace(text))
				return null;
			using (_callback.Open())
				return _speechSynthesizer.SpeakTextAsync(text).Result;
		}

		private class PushAudioOutputMemoryStreamCallback : PushAudioOutputStreamCallback, IDisposable
		{
			private MemoryStream _stream = new MemoryStream();

			public PushAudioOutputMemoryStreamCallback Open()
			{
				_stream?.Close();
				_stream = new MemoryStream();
				return this;
			}

			public override uint Write(byte[] dataBuffer)
			{
				_stream.Write(dataBuffer, 0, dataBuffer.Length);
				return (uint)dataBuffer.Length;
			}

			void IDisposable.Dispose()
			{
				_stream?.Close();
				_stream = null;
				base.Close();
				Dispose();
			}
		}
	}
}
`
 - I was trying to build with VS2019 because building with VS2022 did not include VCRUNTIME140_1.DLL in the output directory which it appears is required by the SDK. I suspect this is also related to [this](https://stackoverflow.com/questions/75616169/unable-to-load-dll-microsoft-cognitiveservices-speech-core-dll-could-not-be-f#answer-75623332)
 - Cannot provide full Speech SDK Log because this happens when the SpeechConfig object is being created
 - Cannot report the SessionId and time (incl. timezone) of the reported incidents.

**Comment by dargilco** [comment]
Thank you @frank-vanderhulst for opening this issue and the detailed description. You can turn on/off logs using the two lines below (not yet documented). Please provide two logs, one when running your VS2019 build (resulting in exception) and one when running your VS2022 build. 
Darren

FYI @yulin-li , @jhakulin 

```
Microsoft.CognitiveServices.Speech.Diagnostics.Logging.FileLogger.Start("path-to-your-logfile.txt");

<< Your Speech SDK API calls here>>

Microsoft.CognitiveServices.Speech.Diagnostics.Logging.FileLogger.Stop();
```

**Comment by dargilco** [comment]
Also @frank-vanderhulst what you reported is on a single machine? or are you compiling VS2019 on one machine and VS2022 on another. I think you are using just one machine for both, just wanted to confirm.
Please run `dotnet --info` on the machine and share the output.

**Comment by frank-vanderhulst** [comment]
Hi @dargilco ,
Thanks for the quick reply ahead of the qweekend.

On my dev box the web app built with VS2022 works perfectly, because I have vcruntime140_1.dll in my Windows\System32 directory. However, if I build it with VS2019, I get an exception
```
{"An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"}
					at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
					at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
```
When I deploy the build to our server and run it, it raises the following exception when I try to do a TTS conversion. Through trial and error I found that this was because the vcruntime140_1.dll file was not included in the build. If I copy it to the bin directory on the server, everything works perfectly. I guess what I really, really want is a way to include that dll in the VS2022 build output.

```
2023-06-09 15:23:20,904 [9] ERROR Admin - An unhandled exception occured. { User: "27026|False|frank.vanderhulstadmin|308c0f0c-e4c0-c67b-8b47-83c1c7e7d4b7", StatusCode: "500", Path: "/PTV/DoTPSAnnouncements.aspx", QueryString: "", Referrer: "https://admin-test.smartrak.com.au/PTV/DoTPSAnnouncements.aspx", UserAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36", ctl00$hSearchId: "", ctl00$cphLeftContent$tbModifyMessage: "1", ctl00$cphLeftContent$tbModifyStartDate: "2023-05-23", ctl00$cphLeftContent$tbModifyEndDate: "2023-05-23", ctl00$cphLeftContent$btnModifyValidate: "Save", ctl00$cphLeftContent$tbCreateAnnouncementName: "", ctl00$cphLeftContent$tbCreateMessage: "", ctl00$cphLeftContent$tbCreateStartDate: "", ctl00$cphLeftContent$tbCreateEndDate: "" }
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
   at Admin.AppCode.Services.TextToSpeechService..ctor() in C:\BuildAgent\work\9b9aeeeb2971445f\Admin\Admin\AppCode\Services\TextToSpeechService.cs:line 34
   at DoT_PSAnnouncements.ValidateAndConvertSpeech(String message, HtmlGenericControl divError, HtmlGenericControl msgError) in C:\BuildAgent\work\9b9aeeeb2971445f\Admin\Admin\PTV\DoTPSAnnouncements.aspx.cs:line 120
   at DoT_PSAnnouncements.SaveModifyPsa() in C:\BuildAgent\work\9b9aeeeb2971445f\Admin\Admin\PTV\DoTPSAnnouncements.aspx.cs:line 145
   at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)


```

Here's dotnet --info on the server

```
Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

Here's dotnet --info on my dev box
```

.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.311 [C:\Program Files\dotnet\sdk]
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by dargilco** [comment]
vcruntime140_1.dll is installed with Microsoft Visual C++ Redistributable 2015 - 2019 (2022) and should be included in the PATH after installed. I think the installer puts it into the system folder. C++ redistributable is required to run Speech SDK apps.

**Comment by pankopon** [comment]
Closed since no update in a month, please open a new issue if more support is needed.
