### ISSUE TITLE
Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE) when using speech translation API in Azure batch node without michphone.

### ISSUE THREAD

**Issue by DapengLi2016** [Azure-Samples/cognitive-services-speech-sdk#2005]
**Describe the bug**

**To Reproduce**
     var config = SpeechTranslationConfig.FromSubscription(this.subscriptionKey, this.region);
        config.SpeechRecognitionLanguage = "en-US";
        config.AddTargetLanguage("zh-CN");
        using (var audioInput = AudioConfig.FromWavFileInput(inputAudioFile))
        using (var recognizer = new TranslationRecognizer(config, audioInput))

**Expected behavior**
Below is the Exception thrown at line AudioConfig.FromWavFileInput(inputAudioFile)):

Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Recognizer.FromConfig(GetRecognizerFromConfigDelegate fromConfig, SpeechConfig speechConfig, AudioConfig audioConfig)
   at Microsoft.CognitiveServices.Speech.Translation.TranslationRecognizer..ctor(SpeechTranslationConfig config, AudioConfig audioConfig)
   at Microsoft.SpeechServices.CustomVoice.SpeechTranslationHandler.TranslateAudioAsync(String inputAudioFile, Language fromLanguage, IEnumerable`1 targetLanguages) in D:\git\SpeechServicesCustomVoice\runtimetts\TtsLib\Handlers\SpeechTranslationHandler.cs:line 46
   at Microsoft.SpeechServices.Backend.CustomVoiceGeneralTaskHost.TranslateVideo.Microsoft.SpeechServices.CustomVoice.TtsLib.Interface.IVoiceGeneralTaskModule.ProcessAsync(IVoiceGeneralTaskInputDataProvider dataProvider, IVoiceGeneralTaskPathProvider pathProvider, GeneralTaskPredefinedOutputFile predefinedOutputResult) in D:\git\SpeechServicesCustomVoice\backend\OfflineProcessing\CustomVoiceGeneralTaskHost\Modules\TranslateVideo.cs:line 199
   at Microsoft.SpeechServices.Backend.CustomVoiceGeneralTaskHost.ConsoleAppExecutor.Microsoft.SpeechServices.Backend.CustomVoiceGeneralTaskHost.IConsoleAppExecutor.ExecuteAsync(Arguments arg) in D:\git\SpeechServicesCustomVoice\backend\OfflineProcessing\CustomVoiceGeneralTaskHost\ConsoleAppExecutor.cs:line 62

Process failed with error message: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)

**Version of the Cognitive Services Speech SDK**
1.30.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: C#
using Console 

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by DapengLi2016** [comment]
Hi, it is because my using the wrong parameter inputAudioFile is empty.
The SDK error message is not correct.

**Comment by pankopon** [comment]
This is indeed an undocumented feature - if `filename` in `AudioConfig.FromWavFileInput(filename)` is an empty string, the SDK reverts to using a microphone by default.

**Comment by pankopon** [comment]
Closed as resolved, please open a new issue if more support is needed.
