### ISSUE TITLE
Can not work on CentOS 7 with  java

### ISSUE THREAD

**Issue by youtianhong** [Azure-Samples/cognitive-services-speech-sdk#2029]
**Describe the bug**
My application is a spring boot java project connecting to the azure services for converting text to speech.
It reported this issue **"java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)"   before** configuring CentOS 7 for this link: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7.
**I have installed all steps as mentioned in the link**，but the issue was changed like below
**java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.cognitiveservices.speech.SpeechConfig**

**To Reproduce**
1. try to convert text to speech on CentOS 7 with  java
2. after installing the configuration CentOS 7 like above link, it always reported "java.lang.NoClassDefFoundError"

**Expected behavior**
Hope will transform text to speech normally on CentOs7  (**It's work fine on Windows OS**)

**Version of the Cognitive Services Speech SDK**
1.30.0 of client-sdk

**Platform, Operating System, and Programming Language**
 - OS: Linux
 - Hardware - x64
 - Programming language: Java
 - Browser: Chrome

**Additional context**
**The whole error stack trace like below:**
java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.cognitiveservices.speech.SpeechConfig
        at com.spacefliggy.aioral.integration.azure.AzureTtsServiceImpl.textToSpeech(AzureTtsServiceImpl.java:23)
        at com.spacefliggy.aioral.web.controller.SpeechController.textToSpeechForAzure(SpeechController.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
 
I have installed all steps except the last step for Environment settings,
**I did not export LD_LIBRARY_PATH for "SpeechSDK lib" with  bold font, because I did not find any like "speech sdk" or speech on centos7**,
It always does not exist, even when I do a global search for all keywords  on centos7, **I'm not sure if this step is causing the problem ?**

//# Add updated C/C++ runtimes to the library path
//# (this is required for any development/testing with Speech SDK)
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH

//# For C++ development only:
//# - add the updated compiler to PATH
//#   (note, /usr/local/bin should be already first in PATH on vanilla systems)
//# - add Speech SDK libraries from the Linux tar package to LD_LIBRARY_PATH
//#   (note, use the actual path to extracted files!)
export PATH=/usr/local/bin:$PATH
hash -r # reset cached paths in the current shell session just in case
**export LD_LIBRARY_PATH=/path/to/extracted/SpeechSDK-Linux-<version>/lib/centos7-x64:$LD_LIBRARY_PATH**

Please don't recommend me to use javascript on linux instead of it.

**Comment by pankopon** [comment]
Please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1769 for things to check and verify.

As the comment says, the last part of environment settings to add Speech SDK libraries to `LD_LIBRARY_PATH` is *For C++ development only*.

**Comment by youtianhong** [comment]
> Please see #1769 for things to check and verify.
> 
> As the comment says, the last part of environment settings to add Speech SDK libraries to `LD_LIBRARY_PATH` is _For C++ development only_.

Thanks for your reply ! Yes, I don't need C++ development environment settings, but running env.

**I find the version of GLIBCXX is not right**, when I printed System.loadLibrary()  and then reported this issue:
2023-07-27 22:53:22.628 [http-nio-6666-exec-1] ERROR o.a.c.c.C.[.[.[/talks].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/talks] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: /opt/talksmart/env_lib/text2speechAzure/centos7-x64/libMicrosoft.CognitiveServices.Speech.java.bindings.so: /lib64/libstdc++.so.6: **version `GLIBCXX_3.4.21' not found** (required by /opt/talksmart/env_lib/text2speechAzure/centos7-x64/libMicrosoft.CognitiveServices.Speech.java.bindings.so)] with root 

2. it's not exist 3.4.21 version when i execute the command, **so how can i get the version of GLIBCXX  3.4.21 ?**
[root@VM-4-9-centos ~]# strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19

**Comment by youtianhong** [comment]
When I upgrade gcc version to 11.2.0, this problem is fixed. but the new problem is happened, when I runned the tts program,
the response result is Canceled, What's the problem? (**It works fine on Windows OS**)

2023-07-28 12:23:16.163 [http-nio-6666-exec-8] INFO  c.s.aioral.web.controller.SpeechController - ---------loadLibrary success------
2023-07-28 12:23:16.163 [http-nio-6666-exec-8] INFO  c.s.aioral.integration.azure.AzureTtsServiceImpl - start to textToSpeech,voiceName=en-US-JaneNeural,text length=12
2023-07-28 12:23:16.545 [http-nio-6666-exec-8] INFO  c.s.aioral.integration.azure.AzureTtsServiceImpl - textToSpeech **resultId=185c66bd97fe4b9c97b124311a3c1be8 reason=Canceled**

**You known the normal response result is** "textToSpeech resultId=8cb690dde3304cfa9fe74c97e2a9b61a，**reason=SynthesizingAudioCompleted**" which was executed on Windows OS

**My text to speech code like below:**
`public byte[] textToSpeech(String voiceName,String text) {
        log.info("start to textToSpeech,voiceName={},text length={}",voiceName,text.length());

        try{

            SpeechConfig speechConfig = SpeechConfig.fromSubscription("4408b323ce244ce7b7b8bxxxxx", "southeastasia");
            speechConfig.setSpeechSynthesisLanguage("en-US");
            //en-US-JennyNeural
            speechConfig.setSpeechSynthesisVoiceName(voiceName);
            speechConfig.setSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat.Audio24Khz48KBitRateMonoMp3);
            SpeechSynthesizer synthesizer = new SpeechSynthesizer(speechConfig, null);
            SpeechSynthesisResult result = synthesizer.SpeakText(text);
            log.info("textToSpeech resultId={}，reason={}",result.getResultId(),result.getReason().toString());
            return result.getAudioData();
        } 
}`

**Comment by pankopon** [comment]
Closed since another issue was opened about the same topic.
