### ISSUE TITLE
Error SPXERR_GSTREAMER_NOT_FOUND_ERROR for MP3 Speech To Test in C#. 

### ISSUE THREAD

**Issue by alixv1** [Azure-Samples/cognitive-services-speech-sdk#2075]
I have the issue when trying to execute the C# program on Win11 (Build 22621.2134) to extract captions from MP3 source.  
GStreamrer is installed with the latest version. (1.22.5) / Microsoft.CognitiveServices.Speech 1.32.1 
netcoreapp3.1 / Platforms x64.

Path contains : C:\gstreamer\1.0\x86_64\bin and   
GSTREAMER_ROOT_X86_64 C:\gstreamer\1.0\x86_64 and 
GSTREAMER_1_0_ROOT_MINGW_X86_64 C:\gstreamer\1.0\mingw_x86_64\
(PC rebooted  after GSTreamer installed)

Error stack : 
Unhandled exception. System.ApplicationException: Exception with an error code: 0x29 (SPXERR_GSTREAMER_NOT_FOUND_ERROR)
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Recognizer.FromConfig(GetRecognizerFromConfigDelegate fromConfig, SpeechConfig speechConfig, AudioConfig audioConfig)
   at Microsoft.CognitiveServices.Speech.SpeechRecognizer..ctor(SpeechConfig speechConfig, AudioConfig audioConfig)
   at Captioning.Program.SpeechRecognizerFromUserConfig() in C:\LocalData\TestMP3ToText\cognitive-services-speech-sdk\scenarios\csharp\dotnetcore\captioning\captioning\Program.cs:line 290
   at Captioning.Program.Main(String[] args) in C:\LocalData\TestMP3ToText\cognitive-services-speech-sdk\scenarios\csharp\dotnetcore\captioning\captioning\Program.cs:line 458

Execution line :  
dotnet run --input "MyMP3File.mp3" --format mp3 --output "C:\temp\getCaption.txt" --offline --threshold 5 --delay 0 --profanity raw

I tried with several mp3, for instance mp3s available on bbc : https://www.bbc.co.uk/programmes/w3ct4mv1 

I tried a workaround ( https://stackoverflow.com/questions/63358132/spxerr-gstreamer-not-found-error-when-using-mp3-file-with-microsoft-cognitiveser) by downgrading GSTreamer version and Microsoft.CognitiveServices.Speech but then there is compilation error, and this is not the good sign of progress. 

The samples provided in  *.wav work fine on my PC / I see mp3 is in the accepted value in FORMAT

As the program propose  MP3 as input is could be great to add sample mp3 files as well in the repo. 

Thank you very much!

**Comment by BrianMouncer** [comment]
@alixv1  I would suggest using GStreamer version 1.18.4, as that is the version we build against and test in our automated tests.

You may also find this information usefull.

https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=windows%2Cdebian%2Cjava-android%2Cterminal&pivots=programming-language-csharp
