### ISSUE TITLE
Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.cognitiveservices.speech.SpeechConfig

### ISSUE THREAD

**Issue by mrwangjing** [Azure-Samples/cognitive-services-speech-sdk#2120]
hi,everyone.
this is my exception

01-Nov-2023 00:59:44.169 SEVERE [http-nio-8081-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [srpingmvc] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V] with root cause
        java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
                at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
                at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(Unknown Source)
                at com.speech.utils.tts.micTts.MicTts.ttsMic(MicTts.java:88)
                at com.speech.service.impl.SpeechSynthesisByteServiceImpl.getAudioByte(SpeechSynthesisByteServiceImpl.java:170)
                at com.speech.service.impl.SpeechSynthesisByteServiceImpl.synthesisTemporary(SpeechSynthesisByteServiceImpl.java:79)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
                at com.sun.proxy.$Proxy50.synthesisTemporary(Unknown Source)
                at com.speech.controller.SpeechSynthesisController.synthesisTemporary(SpeechSynthesisController.java:54)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
                at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
                at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
                at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:367)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1691)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)

[root@VM-4-5-centos ~]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core) 

[root@VM-4-5-centos ~]# java -version
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (build 25.382-b05, mixed mode)

my pom file

<dependency>
      <groupId>com.microsoft.cognitiveservices.speech</groupId>
      <artifactId>client-sdk</artifactId>
      <version>1.31.0</version>
  </dependency>

follow the steps by  https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-configure-rhel-centos-7

finally execete  the following instructions

export LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
export PATH=/usr/local/bin:$PATH
export LD_LIBRARY_PATH=/path/to/extracted/SpeechSDK-Linux-7.9.2009/lib/centos7-x64/:$LD_LIBRARY_PATH

it still not work and threw the same exception 

hepl me  guys.
thank you very much.

**Comment by ralph-msft** [comment]
When running:
```bash
export LD_LIBRARY_PATH=/path/to/extracted/SpeechSDK-Linux-7.9.2009/lib/centos7-x64/:$LD_LIBRARY_PATH
```
You'll need to replace `/path/to/extracted/SpeechSDK-Linux-7.9.2009/` with the correct path on your machine.

**Comment by mrwangjing** [comment]
[root@VM-4-5-centos ~]# echo $LD_LIBRARY_PATH
/root/SpeechSDK-Linux-1.32.1/lib/centos7-x64/:/usr/local/lib64/:/root/speechsdk/lib/centos7-x64/:/usr/local/lib64/:/root/speechsdk/lib/centos7-x64:/usr/local/lib64:/path/to/extracted/SpeechSDK-Linux-7.9/lib/centos7-x64/:/usr/local/lib64/:

i was replace new path on my machine。

![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/26055736/04517362-d6bb-4c4d-b11f-e538f5133670)

[root@VM-4-5-centos centos7-x64]# pwd
/root/SpeechSDK-Linux-1.32.1/lib/centos7-x64
[root@VM-4-5-centos centos7-x64]# ls
libMicrosoft.CognitiveServices.Speech.core.so                 libMicrosoft.CognitiveServices.Speech.extension.kws.so
libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so  libMicrosoft.CognitiveServices.Speech.extension.lu.so
libMicrosoft.CognitiveServices.Speech.extension.codec.so      libMicrosoft.CognitiveServices.Speech.extension.mas.so
libMicrosoft.CognitiveServices.Speech.extension.kws.ort.so

is there anything need to do?

**Comment by zmjAdmin** [comment]
Hi, Sir

**Comment by zmjAdmin** [comment]
Hi, sir
I have the save problem.
Did you solve it?
Thank you!
