### ISSUE TITLE
[TypeError: Cannot set property format of #<AudioConfigImpl> which has only a getter]

### ISSUE THREAD

**Issue by ChristopherTrimboli** [Azure-Samples/cognitive-services-speech-sdk#2227]
Next.js v14 API route. Tried `edge` and normal `nodejs` envs, no differnece. 
Works fine all the way up to:
` const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);`

It complains: `[TypeError: Cannot set property format of #<AudioConfigImpl> which has only a getter]`

Piping ElevenLabs PCM format stream audio, writing to stream buffer, then loading config.

Here is example: just copy paste into any next.js /api route folder and should reproduce.
I don't think this is issue with ElevenLabs audio formats, I tried wav too, all does not work.

```javascript
import { NextRequest, NextResponse } from "next/server";
import {
  AudioConfig,
  AudioInputStream,
  SpeechConfig,
  SpeechSynthesizer,
} from "microsoft-cognitiveservices-speech-sdk";

export const runtime = "nodejs";

export const POST = async (req: NextRequest) => {
  try {
    const { text, voiceId } = await req.json();

    const elevensResp = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}/stream?output_format=pcm_16000`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "xi-api-key": `${process.env.ELEVEN_LABS_API_KEY}`,
        },
        body: JSON.stringify({
          text,
          model: "eleven_monolingual_v2",
        }),
      }
    );

    const elevenStream = elevensResp.body;

    const elevenStreamReader = elevenStream.getReader();

    const pushStream = AudioInputStream.createPushStream();

    while (true) {
      const { done, value } = await elevenStreamReader.read();

      if (done) {
        pushStream.close();
        break;
      }

      pushStream.write(value);
    }

    const audioConfig = AudioConfig.fromStreamInput(pushStream);

    const speechConfig = SpeechConfig.fromSubscription(
      process.env.AZURE_SPEECH_KEY,
      "westus2"
    );

    const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);

    return new Promise((resolve, reject) => {
      synthesizer.speakTextAsync(
        text,
        (result) => {
          resolve(
            NextResponse.json(
              {
                result,
              },
              {
                status: 200,
              }
            )
          );
        },
        (error) => {
          console.log(error);
          reject(
            NextResponse.json(
              {
                error,
              },
              {
                status: 500,
              }
            )
          );
        }
      );
    });
  } catch (err) {
    console.log(err);
    return NextResponse.json(
      {
        error: "Something went wrong",
      },
      {
        status: 500,
      }
    );
  }
};
```

**Expected behavior**

`SpeechSynthesizer` should initialize with `audioConfig` without type issues.

**Version of the Cognitive Services Speech SDK**

Which version of the SDK are you using. 

1.34.0

**Platform, Operating System, and Programming Language**

 - OS: Linux Ubuntu 23.10
 - Hardware - Intel® Core™ i9-10850K × 20
 - Programming language: JavaScript
 - Browser: none, just in Node.js.

**Comment by ChristopherTrimboli** [comment]
bit more detailed log:
```
TypeError: Cannot set property format of #<AudioConfigImpl> which has only a getter
    at set audioOutputFormat [as audioOutputFormat] (webpack-internal:///(rsc)/./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/SynthesisAdapterBase.js:98:53)
    at SpeechSynthesizer.implCommonSynthesizeSetup (webpack-internal:///(rsc)/./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:145:44)
    at new SpeechSynthesizer (webpack-internal:///(rsc)/./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:63:14)
    at eval (webpack-internal:///(rsc)/./app/api/voice/viseme/route.ts:46:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

**Comment by ChristopherTrimboli** [comment]
I console logged the pushStream and looks constructed OK with data in buffer:

```
PushAudioInputStreamImpl {
  privFormat: AudioStreamFormatImpl {
    formatTag: 1,
    bitsPerSample: 16,
    samplesPerSec: 16000,
    channels: 1,
    avgBytesPerSec: 32000,
    blockAlign: 16,
    privHeader: ArrayBuffer {
      [Uint8Contents]: <52 49 46 46 00 00 00 00 57 41 56 45 66 6d 74 20 10 00 00 00 01 00 01 00 80 3e 00 00 00 7d 00 00 02 00 10 00 64 61 74 61 00 00 00 00>,
      byteLength: 44
    }
  },
  privEvents: EventSource {
    privEventListeners: {},
    privIsDisposed: false,
    privConsoleListener: undefined,
    privMetadata: undefined
  },
  privId: '2F2E9CA754E54F808C49A03F540C4869',
  privStream: ChunkedArrayBufferStream {
    privIsWriteEnded: false,
    privIsReadEnded: false,
    privId: '1E30EC7C09AB460F905ABD274F271CFA',
    privReaderQueue: Queue {
      privPromiseStore: [List],
      privIsDrainInProgress: false,
      privIsDisposing: false,
      privDisposeReason: null,
      privList: [List],
      privDetachables: [Array],
      privSubscribers: [List]
    },
    privTargetChunkSize: 3200,
    privNextBufferReadyBytes: 0
  }
}
```

**Comment by ChristopherTrimboli** [comment]
I also tried `while` loop instead of recursive buffer transfer, no effect.

I also tried to construct a WAV file in code with `wavefile` npm lib.

```
    const respBuffer = await elevensResp.arrayBuffer();

    const wav = new WaveFile();
    wav.fromScratch(1, 16000, "16", Buffer.from(respBuffer));
    const wavData = wav.toBuffer();

    const pushStream = AudioInputStream.createPushStream();

    pushStream.write(wavData);
    pushStream.close();

    const audioConfig = AudioConfig.fromWavFileInput(Buffer.from(wavData));
```

this produces exact same Type error: `Cannot set property format of #<AudioConfigImpl> which has only a getter`

**Comment by ChristopherTrimboli** [comment]
I am moving this code out of nextjs and also loading from WAV from disk I believe works, however in Next.js lambda style edge APIs, we cannot dynamically write to /public disk, so if pushStreams are broken, this is major issue for Next.js backend projects, requires me to setup an AWS microservice just to host Azure SDK, or switch to C# lambda.

**Comment by ChristopherTrimboli** [comment]
Moved code to vanilla node.js project with expressJS. Exact same error reproduced.
`Cannot set property format of #<AudioConfigImpl> which has only a getter`

```
import express from "express";
import {
  AudioConfig,
  AudioInputStream,
  SpeechConfig,
  SpeechSynthesizer,
} from "microsoft-cognitiveservices-speech-sdk";
import fetch from "node-fetch";

const app = express();
app.use(express.json()); // for parsing application/json
app.use(express.urlencoded({ extended: true })); // for parsing application/x-www-form-urlencoded

const port = 3001;

const ELEVEN_LABS_API_KEY = "";
const AZURE_SPEECH_KEY = "";

app.post("/voice/viseme", async (req, res) => {
  try {
    const { text, voiceId } = await req.body;

    const elevensResp = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}/stream?output_format=pcm_16000`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "xi-api-key": `${ELEVEN_LABS_API_KEY}`,
        },
        body: JSON.stringify({
          text,
          model: "eleven_monolingual_v2",
        }),
      }
    );

    const respBuffer = await elevensResp.arrayBuffer();

    const pushStream = AudioInputStream.createPushStream();

    pushStream.write(respBuffer);
    pushStream.close();

    const audioConfig = AudioConfig.fromStreamInput(pushStream);

    const speechConfig = SpeechConfig.fromSubscription(
      AZURE_SPEECH_KEY,
      "westus2"
    );

    speechConfig.speechSynthesisLanguage = "en-US";

    const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);

    return new Promise((resolve, reject) => {
      synthesizer.visemeReceived = function (s, e) {
        window.console.log(
          "(Viseme), Audio offset: " +
            e.audioOffset / 10000 +
            "ms. Viseme ID: " +
            e.visemeId
        );
      };
      synthesizer.speakTextAsync(
        text,
        (result) => {
          resolve(res.send(result) as any);
        },
        (error) => {
          console.log(error);
          reject(error);
        }
      );
    });
  } catch (err) {
    console.log(err);
    return;
  }
});

app.listen(port, () => {
  return console.log(`Express is listening at http://localhost:${port}`);
});
```

**Comment by ChristopherTrimboli** [comment]
finally for the grande finale... OK its streaming that does not work...  or maybe need to use SSML... so lets try write to disk audio.wav with SSML different style:

```
import express from "express";
import {
  AudioConfig,
  SpeechConfig,
  SpeechSynthesizer,
} from "microsoft-cognitiveservices-speech-sdk";
import fetch from "node-fetch";
import { WaveFile } from "wavefile";
import fs from "fs";
import path from "path";

const app = express();
app.use(express.json()); // for parsing application/json
app.use(express.urlencoded({ extended: true })); // for parsing application/x-www-form-urlencoded

const port = 3001;

const ELEVEN_LABS_API_KEY = "";
const AZURE_SPEECH_KEY = "";

app.post("/voice/viseme", async (req, res) => {
  try {
    const { text, voiceId } = await req.body;

    const elevensResp = await fetch(
      `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}?output_format=pcm_16000`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "xi-api-key": `${ELEVEN_LABS_API_KEY}`,
        },
        body: JSON.stringify({
          text,
          model: "eleven_monolingual_v2",
        }),
      }
    );

    const respBuffer = await elevensResp.arrayBuffer();

    const wav = new WaveFile();
    wav.fromScratch(1, 16000, "16", Buffer.from(respBuffer));
    const wavData = wav.toBuffer();

    const filePath = path.join(__dirname, "audio.wav");
    fs.writeFileSync(filePath, wavData);

    const audioConfig = AudioConfig.fromWavFileInput(
      Buffer.from(wavData),
      filePath
    );

    const speechConfig = SpeechConfig.fromSubscription(
      AZURE_SPEECH_KEY,
      "westus2"
    );

    speechConfig.speechSynthesisLanguage = "en-US";

    const synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);

    return new Promise((resolve, reject) => {
      synthesizer.visemeReceived = function (s, e) {
        window.console.log(
          "(Viseme), Audio offset: " +
            e.audioOffset / 10000 +
            "ms. Viseme ID: " +
            e.visemeId
        );
      };
      synthesizer.speakSsmlAsync(
        `<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US"><voice name="en-US-JennyNeural">${text}</voice></speak>`,
        (result) => {
          resolve(res.send(result) as any);
        },
        (error) => {
          console.log(error);
          reject(error);
        }
      );
    });
  } catch (err) {
    console.log(err);
    return;
  }
});

app.listen(port, () => {
  return console.log(`Express is listening at http://localhost:${port}`);
});
```

EXACT same error...

```
TypeError: Cannot set property format of #<AudioConfigImpl> which has only a getter
    at set audioOutputFormat [as audioOutputFormat] (/home/cjft/Documents/github/lalaland/lala-speech/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/SynthesisAdapterBase.js:78:53)
    at SpeechSynthesizer.implCommonSynthesizeSetup (/home/cjft/Documents/github/lalaland/lala-speech/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:134:44)
    at new SpeechSynthesizer (/home/cjft/Documents/github/lalaland/lala-speech/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:46:14)
    at /home/cjft/Documents/github/lalaland/lala-speech/src/index.js:50:29
    at Generator.next (<anonymous>)
    at fulfilled (/home/cjft/Documents/github/lalaland/lala-speech/src/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I'm burnt out... no idea. help?

**Comment by rhurey** [comment]
Thanks for getting in touch.

Just to make sure I'm looking at things correctly, is the goal of this to be able to compare TTS output from elevenlabs and Azure Text To Speech?

If that's the case, I believe the problem you're running into is here:
```
    const audioConfig = AudioConfig.fromWavFileInput(
      Buffer.from(wavData),
      filePath
    );
```

That's creating an AudioConfig that represents audio being passed into the Speech SDK, not audio coming from the Speech SDK.

You may want to call fromAudioFileOutput instead and write the audio to disk.

If I've made an incorrect assumption about the goal, can you give a description of what the goal is?

**Comment by ChristopherTrimboli** [comment]
hmm, I might just be confused over `fromWavFileInput` vs. `fromAudioFileOutput`. I will try.

My goal is just to get visemes from a `pcm_16000` audio stream from ElevenLabs, so that I can animate the 3D mouth movements of a VRM web avatar. I do not require Azure audio, but do want the Viseme processed for IDs. I am making my own rigging.

Preferably I could use `pushStream` I thought, instead of needing to write to disk, would be ideal for speed, but I can cope with disk writes for now as long as works... will give update soon.

**Comment by rhurey** [comment]
Ah! Thanks for that clarity.

The Viseme generation is part of the speech synthesis pipeline and isn't invocable standalone request. So the Viseme's are applicable to the audio the Speech Service generates, but can't be generated from existing audio.

**Comment by ChristopherTrimboli** [comment]
ah I see, thanks for clarification, issue resolved.
