### ISSUE TITLE
Couldn't find "libMicrosoft.CognitiveServices.Speech.java.bindings.so"

### ISSUE THREAD

**Issue by XinwenCheng** [Azure-Samples/cognitive-services-speech-sdk#248]
**Describe the bug**
```java
implementation 'com.microsoft.cognitiveservices.speech:client-sdk:1.5.1'
```

I created a demo Android APP with above gradle configuration and ran it on my mobile phone directly, speech recognition works correctly. 

But my real project run on a rooted Android device, I pushed apk under /system/priv-app folder, there's an exception says `Couldn't find "libMicrosoft.CognitiveServices.Speech.java.bindings.so"` when app runs at following line:
```java
SpeechConfig config = SpeechConfig.fromSubscription(BuildConfig.APP_KEY_SPEECH_AZURE, BingUtil.REGION_CODE);
```

There's no such so file in libs/armeabi folder of the generated apk package.

**To Reproduce**
As above.

**Expected behavior**
Works fine on rooted device.

**Version of the Cognitive Services Speech SDK**
com.microsoft.cognitiveservices.speech:client-sdk:1.5.1

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Hardware - ARM
 - Programming language: Java

**Additional context**
05-29 17:21:00.576 1432-1432/com.easyto.translator E/MtaSDK.CaughtExp: MTA has caught the following uncaught exception:
05-29 17:21:00.587 1432-1432/com.easyto.translator E/MtaSDK.CaughtExp: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/easyto/easyto.apk"],nativeLibraryDirectories=[/system/priv-app/easyto/lib/arm, /system/priv-app/easyto/easyto.apk!/lib/armeabi, /vendor/lib, /system/lib]]] couldn't find "libMicrosoft.CognitiveServices.Speech.java.bindings.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:65)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.fromSubscription(SpeechConfig.java:96)
        at com.easyto.translator.strategy.recognize_new.impl.BingRecognize.recognizeStart(BingRecognize.java:54)
        at com.easyto.translator.strategy.recognize_new.impl.BaseRecognize.start(BaseRecognize.java:53)
        at com.easyto.translator.strategy.recognize_new.impl.BingRecognize.start(BingRecognize.java:22)
        at com.easyto.translator.strategy.recognize_new.manager.RecognizeManager.start(RecognizeManager.java:56)
        at com.easyto.translator.strategy.recognize_new.client.RecognizeClient.start(RecognizeClient.java:34)
        at com.easyto.translator.ui.translate.TranslateClientHelper.start(TranslateClientHelper.java:82)
        at com.easyto.translator.ui.translate.TranslateActivity.startRecording(TranslateActivity.java:485)
        at com.easyto.translator.ui.translate.TranslateActivity.access$800(TranslateActivity.java:50)
        at com.easyto.translator.ui.translate.TranslateActivity$TranslateHandler.handleMessage(TranslateActivity.java:203)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5737)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by XinwenCheng** [comment]
Solved, use `armeabi-v7a`.
