### ISSUE TITLE
Talking Avatar Chat Python. Problem with handleUserQuery()

### ISSUE THREAD

**Issue by arifjahangir2413** [Azure-Samples/cognitive-services-speech-sdk#2569]
I have windows 11, I am using python = 3.10.14
I am trying to run Talking Avatar Chat giving it Azure OpenAI Deployment Name, System Prompt, Azure Cognitive Search Index Name. I have created relevant resources in Azure portal. I keep on having this error.
Error: TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at handleUserQuery (chat.js:315:5)
    at speechRecognizer.recognized (chat.js:491:13)
    at SpeechServiceRecognizer.processTypeSpecificMessages (SpeechServiceRecognizer.ts:142:59)
    at SpeechServiceRecognizer.receiveMessage (ServiceRecognizerBase.ts:652:41)
(anonymous) @ chat.js:328
Promise.catch
handleUserQuery @ chat.js:327
speechRecognizer.recognized @ chat.js:491
processTypeSpecificMessages @ SpeechServiceRecognizer.ts:142
receiveMessage @ ServiceRecognizerBase.ts:652
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
recognize @ ServiceRecognizerBase.ts:421
await in recognize
startContinuousRecognitionAsyncImpl @ Recognizer.ts:216
await in startContinuousRecognitionAsyncImpl
startContinuousRecognitionAsync @ SpeechRecognizer.ts:198
window.microphone @ chat.js:495
onclick @ chat:65Understand this error
chat.js:328 Error: TypeError: Failed to execute 'fetch' on 'Window': Invalid value
    at handleUserQuery (chat.js:315:5)
    at speechRecognizer.recognized (chat.js:491:13)
    at SpeechServiceRecognizer.processTypeSpecificMessages (SpeechServiceRecognizer.ts:142:59)
    at SpeechServiceRecognizer.receiveMessage (ServiceRecognizerBase.ts:652:41)
(anonymous) @ chat.js:328
Promise.catch
handleUserQuery @ chat.js:327
speechRecognizer.recognized @ chat.js:491
processTypeSpecificMessages @ SpeechServiceRecognizer.ts:142
receiveMessage @ ServiceRecognizerBase.ts:652
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
receiveMessage @ ServiceRecognizerBase.ts:660
await in receiveMessage
recognize @ ServiceRecognizerBase.ts:421
await in recognize
startContinuousRecognitionAsyncImpl @ Recognizer.ts:216
await in startContinuousRecognitionAsyncImpl
startContinuousRecognitionAsync @ SpeechRecognizer.ts:198
window.microphone @ chat.js:495
onclick @ chat:65Understand this error
chat.js:150 [2024-09-02T01:29:43.720Z] WebRTC event received: {
  "event": {
    "eventType": "EVENT_TYPE_SWITCH_TO_SPEAKING",
    "offset": "299.570s"
  }
}
chat.js:168 WebRTC status: disconnected

**Comment by yinhew** [comment]
Hi, @arifjahangir2413 

Which version of Speech SDK are you using?
Can you try latest version of Speech SDK and see if the issue still persists?

**Comment by pankopon** [comment]
Closing an old item since there was no update from the customer.
