### ISSUE TITLE
Can't run python Avatar guide

### ISSUE THREAD

**Issue by volsh-smart-it** [Azure-Samples/cognitive-services-speech-sdk#2575]
**Describe the bug**
While I am trying to follow the guide for python avatar (samples/python/web/avatar/README.md)
after I have instelled azure-cognitiveservices-speech 1.40.0, Microsoft Visual C++ Redistributable for Visual Studio, set up env variables and trying to run `python -m flask run -h 0.0.0.0 -p 5000`
I am getting an error:

```
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
```

**To Reproduce**

1. Follow the guide https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/web/avatar/README.md up to the end of step 1
2. Run `python -m flask run -h 0.0.0.0 -p 5000`

**Expected behavior**

To proceed with a guide futher

**Version of the Cognitive Services Speech SDK**

Name: azure-cognitiveservices-speech
Version: 1.40.0

**Platform, Operating System, and Programming Language**

 - OS: Windows11 Enterprise
 - Hardware - x64
 - Programming language: Python
**Additional context**

Full error message

```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\samples\python\web\avatar\app.py", line 18, in <module>
    from azure.identity import DefaultAzureCredential
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\__init__.py", line 10, in <module>
    from ._credentials import (
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\_credentials\__init__.py", line 5, in <module>
    from .authorization_code import AuthorizationCodeCredential
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\_credentials\authorization_code.py", line 9, in <module>
    from .._internal.aad_client import AadClient
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\_internal\__init__.py", line 5, in <module>
    from .aad_client import AadClient
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\_internal\aad_client.py", line 11, in <module>
    from .aad_client_base import AadClientBase
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\_internal\aad_client_base.py", line 20, in <module>
    from .aadclient_certificate import AadClientCertificate
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\azure\identity\_internal\aadclient_certificate.py", line 7, in <module>
    from cryptography import x509
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency, verification
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\lib\site-packages\cryptography\x509\certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
```

**Comment by volsh-smart-it** [comment]
Changed python version and it worked
