### ISSUE TITLE
Chat throws 403 Forbidden error

### ISSUE THREAD

**Issue by volsh-smart-it** [Azure-Samples/cognitive-services-speech-sdk#2579]
I am trying to use azure avatar with python.
It works fine in a basic mode, but fails in a chat mode. 
After I have inputed some voice I see it on screen and I am getting:
```
Result id for avatar connection: 2cd46476e6ba451db594393b0f1cbef5
127.0.0.1 - - [09/Sep/2024 22:22:23] "POST /api/connectAvatar HTTP/1.1" 200 -
127.0.0.1 - - [09/Sep/2024 22:22:33] "POST /api/chat HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi       
    execute(self.server.app)
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\Lib\site-packages\werkzeug\serving.py", line 333, in execute        
    for data in application_iter:
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
                ^^^^^^^^^
  File "C:\Users\volsh\Downloads\text-to-speech-sdk\cognitive-services-speech-sdk-master\samples\python\web\avatar\app.py", line 391, in handleUserQuery
    raise Exception(f"Chat API response status: {response.status_code} {response.reason}")
Exception: Chat API response status: 403 Forbidden
```

1. Use guide https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/web/avatar/README.md
2. Get to the step with a Chat Sample
3. run python -m flask run -h 0.0.0.0 -p 5000
4. go to http://localhost:5000/chat
5. try to get any responce from the avatar

**Expected behavior**

I want avatar to respond to my questions

**Version of the Cognitive Services Speech SDK**

azure-cognitiveservices-speech 1.40.0

**Platform, Operating System, and Programming Language**

 - OS: Windows11 enterprise
 - Hardware - x64
 - Programming language: Python
 - Browser: Chrome

**Additional context**
I have entered values for 
- azure_openai_endpoint
- azure_openai_api_key
- azure_openai_deployment_name
and tested that this endpoint and the model deployment are actually active

**Comment by yinhew** [comment]
Hi, @volsh-smart-it 

Does this issue still persist for you based on the latest sample code?

**Comment by pankopon** [comment]
Closing an old item since there was no update from the customer.
