### ISSUE TITLE
com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize() timed out after 60 seconds

### ISSUE THREAD

**Issue by jieqiudede** [Azure-Samples/cognitive-services-speech-sdk#2583]
Fatal Exception: java.util.concurrent.TimeoutException: com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize() timed out after 60 seconds
       at com.microsoft.cognitiveservices.speech.util.SafeHandle.releasePropertyHandle()
       at com.microsoft.cognitiveservices.speech.util.SafeHandle.close(:55)
       at com.microsoft.cognitiveservices.speech.util.SafeHandle.finalize()
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
       at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)
       
       
       And my code: 
      withContext(Dispatchers.IO) {
             SpeechSynthesizer synthesizer = new SpeechSynthesizer(speechConfig, audioConfig);
             SpeechSynthesisResult result = result = synthesizer.SpeakSsmlAsync(ssml).get();
             result.close();
      }

**Comment by jieqiudede** [comment]
Can anyone help me?

**Comment by pankopon** [comment]
Closing an old item without updates.

Please use the latest Speech SDK release (1.50 as of this writing). If issues persist and you have a support plan, create an Azure service support ticket: https://azure.microsoft.com/support/create-ticket
