### ISSUE TITLE
[Multi-Device Conversation] The room parameter is not valid.

### ISSUE THREAD

**Issue by maivanchuong95** [Azure-Samples/cognitive-services-speech-sdk#2638]
Error: 

> Create connection session: S3-1-0002-9ZCC Exception: One or more errors occurred. (Failed with HTTP 400  Bad Request
POST https://dev.microsofttranslator.com/capito/room?api-version=2.0&language=en-AU&roomId=LYKPI
X-RequestId: CPRM.SG2P.EE53.1023T0723.10F608
Content-Type: text/plain; charset=utf-8
{"error":{"code":400027,"message":"The room parameter is not valid."}})
 StackTrace:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

**Describe the bug**

The participant cannot join the conversation.

**To Reproduce**

1. Create a conversation. Get conversation ID.
2. Participants join the above conversation with the conversation ID.
3. Then the participant exits the conversation with the command: _conversationTranslator?.LeaveConversationAsync(). BUT not receiving LeftConverasation event.
4. Repeat (3) about over 10 times. Then I get an error and can't join the conversation with any name.

**Expected behavior**

The participant can join the conversation.

**Version of the Cognitive Services Speech SDK**

Latest

**Platform, Operating System, and Programming Language**

 - OS: Windows
 - Hardware - x64
 - Programming language: C#

**Comment by pankopon** [comment]
Closing the item due to the feature retirement in June/2026.
