### ISSUE TITLE
SDK does not work with .net framework 

### ISSUE THREAD

**Issue by 1Click1Life** [Azure-Samples/cognitive-services-speech-sdk#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Compile program using .NET Framework 
### Any log messages given by the failure
>
An application error occurred. Please contact the adminstrator with the following information:

The type initializer for 'Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE' threw an exception.

Stack Trace:
   at Microsoft.CognitiveServices.Speech.Internal.carbon_csharpPINVOKE.SpeechFactory_FromSubscription(String jarg1, String jarg2)
   at Microsoft.CognitiveServices.Speech.Internal.SpeechFactory.FromSubscription(String subscription, String region)
   at Microsoft.CognitiveServices.Speech.SpeechFactory.FromSubscription(String subscriptionKey, String region)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Expected/desired behavior
>Not throw the above error when using speech

### OS and Version?
> Windows 10.

### Versions
>

### Mention any other details that might be useful

We need to be able to use this SDK using .net framework because we have a lot of code that can't easily be ported to .net core

Thanks for you help

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wolfma61** [comment]
we support .net framework as described here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-csharp-dotnet-windows

make sure you also select x64 or x86 in the configuration manager ...

does this help already?

thx
Wolfgang

**Comment by wolfma61** [comment]
no reply for a long while, much more extensive support by the SDK since then ....
