### ISSUE TITLE
Cannot import python sdk

### ISSUE THREAD

**Issue by MoizAhmedd** [Azure-Samples/cognitive-services-speech-sdk#376]
**Describe the bug**
Have installed the speech module using pip install azure-cognitiveservices-speech
I've checked my Python lib and site packages folder, the speech module is there.
However when I use import azure.cognitiveservices.speech , and try to run.
I get the following error

Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 27, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "speech_analysis.py", line 5, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\speech\__init__.py", line 8, in <module>
    from .speech import *
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 33, in <module>
    _speech_py_impl = swig_import_helper()
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 31, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_speech_py_impl'

**Comment by chlandsi** [comment]
This sounds like a path issue. Can you verify that the file `Microsoft.CognitiveServices.Speech.core.dll` exists in the `C:\Users\ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\azure\cognitiveservices\speech\` folder, and that this is the correct library path for the  Python you are using?
Could you try to install the module in a [virtualenv](https://virtualenv.pypa.io/en/stable/) or [venv](https://docs.python.org/3/library/venv.html#module-venv)? Thanks!

**Comment by jhakulin** [comment]
Closing the issue. let us know if you still see the issue. Thanks.
