### ISSUE TITLE
error:"..../lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so" too long

### ISSUE THREAD

**Issue by 1293173231** [Azure-Samples/cognitive-services-speech-sdk#380]
When starting your sample in my androidstudio, then it fail.
Please help me! Thanks! This is the error logs:

09-20 16:40:28.051 25784-25784/com.microsoft.cognitiveservices.speech.samples.quickstart E/art: dlopen("/data/app/com.microsoft.cognitiveservices.speech.samples.quickstart-1/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so", RTLD_LAZY) failed: dlopen failed: library name "/data/app/com.microsoft.cognitiveservices.speech.samples.quickstart-1/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so" too long
09-20 16:40:28.051 25784-25784/com.microsoft.cognitiveservices.speech.samples.quickstart D/AndroidRuntime: Shutting down VM
09-20 16:40:28.052 25784-25784/com.microsoft.cognitiveservices.speech.samples.quickstart E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microsoft.cognitiveservices.speech.samples.quickstart, PID: 25784
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:389)
        at android.view.View.performClick(View.java:4848)
        at android.view.View$PerformClick.run(View.java:20262)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384)
        at android.view.View.performClick(View.java:4848) 
        at android.view.View$PerformClick.run(View.java:20262) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library name "/data/app/com.microsoft.cognitiveservices.speech.samples.quickstart-1/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so" too long
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:65)
        at com.microsoft.cognitiveservices.speech.samples.quickstart.MainActivity.onSpeechButtonClicked(MainActivity.java:45)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384) 
        at android.view.View.performClick(View.java:4848) 
        at android.view.View$PerformClick.run(View.java:20262) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
09-20 16:40:28.053 25784-25809/com.microsoft.cognitiveservices.speech.samples.quickstart D/Surface: Surface::setBuffersDimensions(this=0x7fa460c600,w=800,h=1280)
09-20 16:40:34.929 25784-25784/com.microsoft.cognitiveservices.speech.samples.quickstart I/Process: Sending signal. PID: 25784 SIG: 9

**Comment by jhakulin** [comment]
Apologies for very long response time. this issue has newer been seen in our side.

Based on some information from the internet, this may be issue with Android 5.x device, do you use that ? See similar issue https://github.com/termux/termux-app/issues/213
