### ISSUE TITLE
Unable to run batch transcription API from Python

### ISSUE THREAD

**Issue by vikramkute** [Azure-Samples/cognitive-services-speech-sdk#403]
1. Followed all the steps from "https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/README.md"

I have subscription key with S0 account and region is eastus and storage account with mp3 files.

**Expected behavior**
main.py should run successfully.

**Version of the Cognitive Services Speech SDK**
2.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: Python
 - Browser: Chrome

**Error:**

Starting transcription client...
2019-10-15 13:58:03,794 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /api/speechtotext/v2.0/transcriptions
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /api/speechtotext/v2.0/transcriptions
2019-10-15 13:58:03,795 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /api/speechtotext/v2.0/transcriptions
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /api/speechtotext/v2.0/transcriptions
2019-10-15 13:58:03,796 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /api/speechtotext/v2.0/transcriptions
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /api/speechtotext/v2.0/transcriptions
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 135, in <module>
    transcribe()
  File "main.py", line 49, in transcribe
    transcriptions: List[cris_client.Transcription] = transcription_api.get_transcriptions()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\api\custom_speech_transcriptions_api.py", line 415, in get_transcriptions
    (data) = self.get_transcriptions_with_http_info(**kwargs)  # noqa: E501
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\api\custom_speech_transcriptions_api.py", line 487, in get_transcriptions_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\api_client.py", line 351, in request
    headers=headers)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\rest.py", line 238, in GET
    query_params=query_params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\swagger_client\rest.py", line 211, in request
    headers=headers)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\request.py", line 76, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eastus.cris.ai', port=443): Max retries exceeded with url: /api/speechtotext/v2.0/transcriptions (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000197EC0C1DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by chlandsi** [comment]
This looks like a network connection problem. Please double-check that the speech service region is correct, and that you can connect to `<region>.cris.ai`.
For more info, could you add the line `configuration.debug = True` to the code around line 40 in the sample, and post the output? Please make sure to remove any keys from the log. Thanks!

**Comment by chlandsi** [comment]
Unfortunately, the autogenerated client only supports unauthenticated proxies. You can use those by setting `configuration.proxy = 'http://localhost:3128/'` on the Configuration object. If your proxy requires authentication, a quick hack would be to change the `rest.py` file that is installed with the swagger_client package. It uses [urllib](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.poolmanager.ProxyManager) to build the connection to the REST API, you should be able to do something similar to [this](https://github.com/Kaggle/kaggle-api/pull/94/files/68f5b9fb7b04d20cfea36c09e8dc34fa511050e1#diff-23aa26d3e8b43cd0ac60fd0d112d14c5) to get proxy auth working (I haven't had time to test this though).

**Comment by vikramkute** [comment]
I have made following changes as suggested.

In main.py

```configuration.proxy = "http://username:password@proxy.companyname.com:9090"```

In rest.py
```
if configuration.proxy:
            proxy_url = urllib3.util.parse_url(configuration.proxy)
            proxy_hostport = '{}://{}:{}'.format(proxy_url.scheme, proxy_url.host, proxy_url.port) if proxy_url.port else '{}://{}'.format(proxy_url.scheme, proxy_url.host)
            proxy_auth = urllib3.make_headers(proxy_basic_auth=proxy_url.auth) if proxy_url.auth else None

            self.pool_manager = urllib3.ProxyManager(
                num_pools=pools_size,
                maxsize=maxsize,
                cert_reqs=cert_reqs,
                ca_certs=ca_certs,
                cert_file=configuration.cert_file,
                key_file=configuration.key_file,
		proxy_url=proxy_hostport,
                proxy_headers=proxy_auth
            )
```

Unable to bypass proxy. Any suggestions?

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eastus.cris.ai', port=443): Max retries exceeded with url: /api/speechtotext/v2.0/transcriptions (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 blank')))
```

**Comment by chlandsi** [comment]
Hi @vikramkute, I'm sorry, but this is hard to debug without having access to the proxy. You might want to turn on the urllib debug mode (see above) to see the messages from the proxy, and maybe find out if it uses an unusual authentication method. If that turns out to not work, you can still access the API directly (see https://eastus.cris.ai/swagger/ui/index) for example via curl, which should have more options for proxy authentication.

**Comment by vikramkute** [comment]
Thank you @chlandsi The updates you have suggested for rest.py were perfect. I was not able to bypass proxy because of some special characters in my username and password and I was encoding them.

This is how I fixed it.

username: abc\xyz
password: xyz#123456

In main.py
```
configuration = cris_client.Configuration()
configuration.api_key['Ocp-Apim-Subscription-Key'] = SUBSCRIPTION_KEY
configuration.host = "https://{}.cris.ai".format(SERVICE_REGION)
configuration.proxy = "http://iproxy.appl.chrysler.com:9090"
configuration.creds = "abc\\xyz:xyz#123456"  # skip \ and do not encode special chars in password 
```
In rest.py

```
if configuration.proxy:
            self.pool_manager = urllib3.ProxyManager(
                num_pools=pools_size,
                maxsize=maxsize,
                cert_reqs=cert_reqs,
                ca_certs=ca_certs,
                cert_file=configuration.cert_file,
                key_file=configuration.key_file,
                proxy_url=configuration.proxy,
                proxy_headers=urllib3.make_headers(proxy_basic_auth=configuration.creds)
            )
```
