### ISSUE TITLE
java.lang.UnsatisfiedLinkError in Java virtual-assistant sample code

### ISSUE THREAD

**Issue by lhp620** [Azure-Samples/cognitive-services-speech-sdk#465]
**Describe the bug**
When I tried to run /cognitive-services-speech-sdk/quickstart/java/jre/virtual-assistant/ sample code, I got "Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()'"

**To Reproduce**
1. git clone this repo
2. Open Eclipse to launch sample code under /cognitive-services-speech-sdk/quickstart/java/jre/virtual-assistant/
3. Fill the subscriptionkey and region
4. run the sample code

**Expected behavior**
virtual-assistant sample works, as I have created the background bot service according to https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk 

**Version of the Cognitive Services Speech SDK**
1.8.0

**Platform, Operating System, and Programming Language**
 - OS: Windows 10
 - Hardware - x64
 - Programming language: Java with jdk-13.0.1
 - Browser Chrome

**Additional context**
Here is the full exception message:
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()'
	at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init(Native Method)
	at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.<clinit>(carbon_javaJNI.java:958)
	at com.microsoft.cognitiveservices.speech.dialog.DialogServiceConfig.<clinit>(DialogServiceConfig.java:73)
	at com.speechsdk.quickstart.Main.main(Main.java:55)

**Comment by lhp620** [comment]
tried on another machine with Windows 10 X64, Java 8, and Speech SDK 1.8 still get the same error as above. Java info in this box:

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**Comment by lhp620** [comment]
Please move the 
// Set audio input from microphone.
        final AudioConfig audioConfig = AudioConfig.fromDefaultMicrophoneInput();

above the BotFrameworkConfig. After this change, it works on my environment.
