### ISSUE TITLE
Error Running On Raspberry Pi Runnig Ubuntu MATE

### ISSUE THREAD

**Issue by efraimnewman** [Azure-Samples/cognitive-services-speech-sdk#594]
**Describe the bug**
I am trying to use intent recognition on raspberry pi running ubuntu mate (32 bit), using c# and .net core.
when I run the app I get this error:
```
Unhandled exception. System.ApplicationException: Exception with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.KeywordRecognitionModel.FromFile(String fileName)
   at SmartHomeVoice.Services.ListeningService.StartAsync(CancellationToken cancellationToken) in E:\Efraim's stuff\SmartHomeVoice\SmartHomeVoice\Services\ListeningService.cs:line 142
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at SmartHomeVoice.Program.Main() in E:\Efraim's stuff\SmartHomeVoice\SmartHomeVoice\Program.cs:line 19
Aborted
```
other apps that use the microphone are working fine

**To Reproduce**
I used a fresh installation of ubuntu MATE for RPi. I am using a webCam as a microphone.

**Version of the Cognitive Services Speech SDK**
I am using version 1.11 which is supposed to support linux-arm.

**Platform, Operating System, and Programming Language**
 - OS:Ubuntu MATE for Raspberri Pi 32 bit 
 - Hardware - ARM (Raspberry Pi 3B)
 - Programming language: C#, .NET Core 3.0

the output of `lsb_release -a` is:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

**Comment by efraimnewman** [comment]
I already opened this issue over [here](https://github.com/MicrosoftDocs/azure-docs/issues/52932), but I was asked to reopen on this repo

**Comment by jhakulin** [comment]
@efraimnewman Seems that the keyword model file you give to Microsoft.CognitiveServices.Speech.KeywordRecognitionModel.FromFile(String fileName) is failing as file is not found. Do you provide absolute path to file ?

**Comment by efraimnewman** [comment]
Thank you that worked. I also needed to use the fix mentioned [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/587) but now I have different error:
```
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 3597799991
Failed to regester memfd mempool. Reason: could not attach memfd SHM ID to pipe
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 710812132
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 269852665
Ignoring received block reference with non-registered memfd ID = 269852665
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
```
can this be caused by the Text To Speech that I am using or is it something else?

**Comment by efraimnewman** [comment]
I see that I am only getting this error sometimes but the app works normally. I can say this issue is solved. Thank you so much
