### ISSUE TITLE
Filter out [CALL STACK BEGIN]... [CALL STACK END] from Console

### ISSUE THREAD

**Issue by lfcnassif** [Azure-Samples/cognitive-services-speech-sdk#597]
Hello,
I am developing a module for my organization using java client API. Often I get printed in Console [CALL STACK BEGIN]... [CALL STACK END] for problematic/corrupted audios. That could confuse our advanced users that use the app through command line. We don't have control over the audios we receive. I am already redirecting stderr and stdout to an error log using System.setOut() and System.setErr(), and that works for other libs, but do not work for java client sdk. Please, any way to filter out those traces from Console or to turn it off?

**Comment by oscholz** [comment]
@lfcnassif I reached out to the team to find somebody to answer the question for you. Thank you for reaching out!

**Comment by lfcnassif** [comment]
@oscholz thank you for your attention!

**Comment by amitkumarshukla** [comment]
@lfcnassif Could you please paste the full call stack which you are seeing ?

**Comment by lfcnassif** [comment]
Hi @amitkumarshukla, I closed my console windows, but managed to simulate the non asked prints in console passing an invalid subscription key:
```
[CALL STACK BEGIN]

    > source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - source_lang_config_release

    - recognizer_stop_keyword_recognition_async_wait_for

    - recognizer_create_speech_recognizer_from_auto_detect_source_lang_config

    - 00007FFA833525E4 (SymFromAddr() error: Tentativa de acessar endereþo invßlido.)

    - Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_SpeechRecognizer_1FromConfig_1_1SWIG_12

    - 00000000032A7F74 (SymFromAddr() error: NÒo foi possÝvel encontrar o m¾dulo especificado.)

[CALL STACK END]
```

The java stacktrace is below, but I explicitly printed it to paste here. The issue is the stack above, printed to Console, even if I redirect java stderr and stdout at the beginning of the program, and before loading classes of client-sdk-1.11.0.jar, with System.setOut() and System.setErr().
```
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.SpeechRecognizer_FromConfig__SWIG_2(Native Method) ~[client-sdk-1.11.0.jar:?]
        at com.microsoft.cognitiveservices.speech.internal.SpeechRecognizer.FromConfig(SpeechRecognizer.java:51) ~[client-sdk-1.11.0.jar:?]
        at com.microsoft.cognitiveservices.speech.SpeechRecognizer.<init>(SpeechRecognizer.java:97) ~[client-sdk-1.11.0.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AudioTranscriptTask.process(AudioTranscriptTask.java:305) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:221) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:160) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:202) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:168) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:172) [iped-engine-3.17.2.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:233) [iped-engine-3.17.2.jar:?]
```
Thank you

**Comment by amitkumarshukla** [comment]
@lfcnassif  I am really sorry for the delay in responding. I am looking into the trace. If possible could you please provide me how did you repro this ? 

What platfrom ?
Which JDK version ?
possible code snippet ?
Audio file ?

Thank you

**Comment by pankopon** [comment]
@lfcnassif Is this still a valid issue for you? What is the OS environment where your users will run the app, Windows or Linux/Unix-like? If the latter, you could utilize a simple wrapper script to filter out the unwanted console output from native libs that the Speech SDK for Java uses.

**Comment by lfcnassif** [comment]
Windows and Linux OSes. Sorry for not answering. We use console to warn users about important infos and would like to filter out garbage. Will answer the other questions on Sunday or Monday. Tomorrow I am very busy...

**Comment by oscholz** [comment]
@lfcnassif Luis, I will close the issue for now. When you get back to this, please reopen the issue. That will be a signal to us to get back to you more quickly! We look forward to hearing back from you.
