### ISSUE TITLE
java samples issue;Cannot construct instance

### ISSUE THREAD

**Issue by bmwshop** [Azure-Samples/cognitive-services-speech-sdk#662]
Trying to run the java assistant example
Using eclipse 4.15 on Ubuntu 18.04 with openjdk 1.8

**To Reproduce**
Load the project into eclipse, run it

**Expected behavior**
works!

**Version of the Cognitive Services Speech SDK**
 <version>4.6.0-preview3</version>
whatever the pom has

**Platform, Operating System, and Programming Language**
Linux 
 - Hardware - x64
Java

[Thread-0] INFO com.speechsdk.quickstart.Main - Session started event. Session id: ce4cb09c-4688-4d61-ba77-67942c09174e 
[Thread-1] INFO com.speechsdk.quickstart.Main - Received activity with audio: {"channelId":"directlinespeech","conversation":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8","isGroup":false},"from":{"id":"olgabotbot","name":"olgabotbot"},"id":"7e1fef78-f6d1-4b85-9eee-6a21d5478d4a","inputHint":"acceptingInput","recipient":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8|0000"},"replyToId":"d86d7992-7149-4c5c-afa4-116cea01085f","serviceUrl":"urn:botframework:websocket:directlinespeech","speak":"Hello and welcome!","text":"Hello and welcome!","timestamp":"2020-05-22T01:23:33.6243019Z","type":"message"}
[Thread-1] ERROR com.speechsdk.quickstart.Main - IO exception thrown when deserializing the bot response. ErrorMessage:
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.OffsetDateTime` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2020-05-22T01:23:33.6243019Z')
 at [Source: (String)"{"channelId":"directlinespeech","conversation":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8","isGroup":false},"from":{"id":"olgabotbot","name":"olgabotbot"},"id":"7e1fef78-f6d1-4b85-9eee-6a21d5478d4a","inputHint":"acceptingInput","recipient":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8|0000"},"replyToId":"d86d7992-7149-4c5c-afa4-116cea01085f","serviceUrl":"urn:botframework:websocket:directlinespeech","speak":"Hello and welcome!","text":"Hello and welcome!","timestamp":"2020-05-22T01:23:33.6243019Z"[truncated 19 chars]; line: 1, column: 472] (through reference chain: com.microsoft.bot.schema.Activity["timestamp"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1589)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1055)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.speechsdk.quickstart.Main.lambda$6(Main.java:150)
	at com.microsoft.cognitiveservices.speech.util.EventHandlerImpl.fireEvent(EventHandlerImpl.java:94)
	at com.microsoft.cognitiveservices.speech.dialog.DialogServiceConnector.activityReceivedEventCallback(DialogServiceConnector.java:383)
Starting playback.
[main] INFO com.speechsdk.quickstart.Main - DialogServiceConnector is listening...
[Thread-2] WARN com.speechsdk.quickstart.Main - No speech was recognized. Try running the program again.
[Thread-3] INFO com.speechsdk.quickstart.Main - Received activity with audio: {"channelId":"directlinespeech","conversation":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8","isGroup":false},"from":{"id":"olgabotbot","name":"olgabotbot"},"id":"e9b6201a-6195-4cdf-b4a5-d6d8374b0ca2","inputHint":"acceptingInput","recipient":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8|0000"},"replyToId":"ce4cb09c-4688-4d61-ba77-67942c09174e","serviceUrl":"urn:botframework:websocket:directlinespeech","speak":"Echo: undefined","text":"Echo: undefined","timestamp":"2020-05-22T01:23:38.0761351Z","type":"message"}
[Thread-3] ERROR com.speechsdk.quickstart.Main - IO exception thrown when deserializing the bot response. ErrorMessage:
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.OffsetDateTime` (no Creators, like default construct, exist): no String-argument constructor/factory method to deserialize from String value ('2020-05-22T01:23:38.0761351Z')
 at [Source: (String)"{"channelId":"directlinespeech","conversation":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8","isGroup":false},"from":{"id":"olgabotbot","name":"olgabotbot"},"id":"e9b6201a-6195-4cdf-b4a5-d6d8374b0ca2","inputHint":"acceptingInput","recipient":{"id":"0a6b58c0-9324-46b4-8165-fe7f9da060d8|0000"},"replyToId":"ce4cb09c-4688-4d61-ba77-67942c09174e","serviceUrl":"urn:botframework:websocket:directlinespeech","speak":"Echo: undefined","text":"Echo: undefined","timestamp":"2020-05-22T01:23:38.0761351Z","typ"[truncated 13 chars]; line: 1, column: 466] (through reference chain: com.microsoft.bot.schema.Activity["timestamp"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1589)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1055)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.speechsdk.quickstart.Main.lambda$6(Main.java:150)
	at com.microsoft.cognitiveservices.speech.util.EventHandlerImpl.fireEvent(EventHandlerImpl.java:94)Starting playback.
	at com.microsoft.cognitiveservices.speech.dialog.DialogServiceConnector.activityReceivedEventCallback(DialogServiceConnector.java:383)

[main] ERROR com.speechsdk.quickstart.Main - Did not receive any response fom bot.
[main] INFO com.speechsdk.quickstart.Main - Closing connection.
[Thread-8] INFO com.speechsdk.quickstart.Main - Session stopped event. Session id: ce4cb09c-4688-4d61-ba77-67942c09174e

**Comment by oscholz** [comment]
Thank you for this bug report @bmwshop!
I've added this to our backlog. We will review this and if we can repro it, will address it in a future release. Once the work is done, we will update this issue to let you know what release the feature/fix will be in.
In the meantime, you can always try the latest release of the Speech SDK (v. 1.12.1) and see if this still repros. If you do please let us know what you find by commenting in this issue.

**Comment by trrwilson** [comment]
This took a while to get off the backlog and apologies for that.

Searching around, this is a common issue with the external fasterxml dependency related to the JRE version used. My best guess is that the code in the quickstart was verified in a more recent JRE before being pasted into the 1.8 template (it works, as a data point, with zulu14).

A suggested workaround (beyond using --add-opens to weaken the reflection restrictions) is to use an extended ObjectMapper that has a more explicit DateTime deserialization strategy. I found an example of this here (unaffiliated project): https://github.com/klarna/kco_rest_java/issues/12#issuecomment-559496884

This approach (simplified using an anonymous class initializer in the same file instead of an extra named class) will be included in the next release's samples drop. In the meantime, if you or any other reader is still encountering the issue, the steps:

1. Add the annotations lib to the pom.xml dependencies:
```
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.0</version>
        </dependency>
```

2. Change the ObjectMapper initialization:
```
    private static final ObjectMapper mapper = new ObjectMapper()
    {
        {
            this.registerModule(new JodaModule());
            this.registerModule(new JavaTimeModule());
            this.findAndRegisterModules();
            this.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
            this.setSerializationInclusion(JsonInclude.Include.NON_NULL);
            this.setDateFormat(new SimpleDateFormat());
        }
    };
```

This (plus resolving the new imports) will make the deserialization error go away.

Thanks again!
