### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()

### ISSUE THREAD

**Issue by moeschl95** [Azure-Samples/cognitive-services-speech-sdk#692]
**Describe the bug**
When running the code inside IntelliJ everything is fine. But when I build a jar-file using gradle I get the following error message:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()'
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init(Native Method)
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.<clinit>(carbon_javaJNI.java:893)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:70)
        at com.xx.xx.main(ProtoApplication.java:14)
        ... 8 more

What could I do about it? As the jar file has quite some size (> 50 MB including other libraries) missing dependencies shouldn't be the problem.

Using SDK 1.7.0

**Platform, Operating System, and Programming Language**
 - Windows 10 x64
 - Hardware -  Intel x64
 - Programming language: JAVA

**Comment by jhakulin** [comment]
@moeschl95 Thanks for your question, your SDK is quite old, could update first to the latest 1.12.1 and let us know if there is still a problem?

**Comment by moeschl95** [comment]
Updating the SDK worked, looks good now. MANY thanks! I wasn't aware that we used such an old version.

**Comment by jhakulin** [comment]
Great, closing, let us know if problems arises.
