### ISSUE TITLE
Unity Android project crashes (now with logs from Android 9)

### ISSUE THREAD

**Issue by johnseghersmsft** [Azure-Samples/cognitive-services-speech-sdk#78]
**Describe the bug**
I am invoking speech recognition from a Unity app on Android. When I call recognizeOnceAsync(), the app immediately dies with no crash report in the Android logs other than "app has died". I have successfully built and run the Android Sample apps using my subscription key and those are working.

I would appreciate any help you may be able to provide.

**To Reproduce**
This Java method is being run on the Android UI thread (I had been running it on the Unity thread and thought that might be an issue, so I tried the UI thread, no difference observed). I've added copious logging via Android Log calls. There are also callbacks to Unity showing that the connection back to Unity is working.
```
    public void StartRecognitionUI()
    {

        ///////////////////////////////////////////////////
        // recognize with intermediate results
        ///////////////////////////////////////////////////

        Log.d("Unity:SpeechEngine", "StartRecognitionUI");
        try {
            final SpeechConfig speechConfig = SpeechConfig.fromSubscription(SpeechSubscriptionKey, SpeechRegion);
            final AudioConfig audioInput = AudioConfig.fromDefaultMicrophoneInput();
            Log.d("Unity:SpeechEngine", "Got audioInput");
            final SpeechRecognizer reco = new SpeechRecognizer(speechConfig, audioInput);
            Log.d("Unity:SpeechEngine", "Got Recgonizer");

            reco.recognizing.addEventListener(new EventHandler<SpeechRecognitionEventArgs>() {
                public void onEvent(Object o, SpeechRecognitionEventArgs speechRecognitionResultEventArgs)
                {
                    Log.d("Unity:SpeechEngine", "onEvent");
                    try {
                        final String s = speechRecognitionResultEventArgs.getResult().getText();
                        Log.d("Unity:SpeechEngine", "onEvent hypothesis: " + s);
                        _speechCallbacks.Log("Intermediate result received: " + s);
                        _speechCallbacks.HypothesisReceived(s);
                        Log.d("Unity:SpeechEngine", "Callbacks done");
                    } catch (Exception ex) {
                        Log.d("Unity:SpeechEngine", "Exception during hypothesis Event handler\n" + formatException(ex));
                    }
                }
            });

            _speechCallbacks.Log("Starting Speech Recognition");
            Log.d("Unity:SpeechEngine", "Starting Speech Recognition");

            final Future<SpeechRecognitionResult> task = reco.recognizeOnceAsync();

// **** NOTE: This is where the app dies. The next Log call is never made. ****
// **** I am making a similar comment in the logs posted below ****

            Log.d("Unity:SpeechEngine", "Got Future task, isDone:" + task.isDone());
            setOnTaskCompletedListener(task, new OnTaskCompletedListener<SpeechRecognitionResult>() {
                public void onCompleted(SpeechRecognitionResult result)
                {
                    Log.d("Unity:SpeechEngine", "onCompleted");

                    try {
                        final String s = result.getText();
                        Log.d("Unity:SpeechEngine", "result: " + s);
                        reco.close();
                        Log.d("Unity:SpeechEngine", "reco.closed");
                        _speechCallbacks.Log("Recognizer returned: " + s);
                        _speechCallbacks.ResultReceived(s);
                        Log.d("Unity:SpeechEngine", "Callbacks done");
                    } catch (Exception ex) {
                        Log.d("Unity:SpeechEngine", "Exception during hypothesis Event handler\n" + formatException(ex));
                    }
                }
            });
            Log.d("Unity:SpeechEngine", "TaskCompletedListener started");
            
        } catch (Exception ex) {
            _speechCallbacks.LogError(formatException(ex));
        }
    }
```

**Expected behavior**
I expect that the speech recognition should start instead of crashing

**Version of the Cognitive Services Speech SDK**
client-sdk-1.0.0.aar (Android)

**Platform, Operationg System, and Programming Language**
 - OS: Android Google Pixel 2 running Oreo 8.1
 - Hardware - ARM. (compiling for ARMv7)

**Additional context**
This is the logcat output from pushing the button to start recognition through to after the crash. There is some "NOTE ****" comments added by me in the list. There is a consistent exception logged **after** the app has died.
```
2018-10-15 19:23:28.086 16832-16856/johnse.test.speech D/Unity:SpeechEngine: StartRecognition
2018-10-15 19:23:28.087 16832-16832/johnse.test.speech D/Unity:SpeechEngine: StartRecognitionUI
2018-10-15 19:23:28.119 16832-16832/johnse.test.speech D/Unity:SpeechEngine: Got audioInput
2018-10-15 19:23:28.124 16832-16832/johnse.test.speech D/Unity:SpeechEngine: Got Recgonizer
2018-10-15 19:23:28.131 16832-16832/johnse.test.speech I/Unity: Starting Speech Recognition
     
    (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
2018-10-15 19:23:28.131 16832-16832/johnse.test.speech D/Unity:SpeechEngine: Starting Speech Recognition

NOTE **** This is where recognizeOnceAsync() is called and the app dies.

2018-10-15 19:23:28.379 1102-1205/? W/InputDispatcher: channel '1921ccf johnse.test.speech/johnse.test.speech.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2018-10-15 19:23:28.379 1102-1205/? E/InputDispatcher: channel '1921ccf johnse.test.speech/johnse.test.speech.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2018-10-15 19:23:28.380 607-627/? E/SurfaceFlinger: Failed to find layer (SurfaceView - johnse.test.speech/johnse.test.speech.UnityPlayerActivity#0) in layer parent (no-parent).
2018-10-15 19:23:28.380 1102-1429/? I/MediaFocusControl: AudioFocus  removeFocusStackEntryOnDeath(): removing entry for android.os.BinderProxy@e68ef1c
2018-10-15 19:23:28.380 607-828/? E/SurfaceFlinger: Failed to find layer (Background for - SurfaceView - johnse.test.speech/johnse.test.speech.UnityPlayerActivity#0) in layer parent (no-parent).
    
    --------- beginning of system
2018-10-15 19:23:28.380 1102-1120/? I/ActivityManager: Process johnse.test.speech (pid 16832) has died: fore TOP 
2018-10-15 19:23:28.380 1102-1130/? W/zygote64: kill(-16832, 9) failed: No such process
2018-10-15 19:23:28.380 1102-1130/? I/zygote64: Successfully killed process cgroup uid 10127 pid 16832 in 0ms
2018-10-15 19:23:28.381 1102-1429/? I/WindowManager: WIN DEATH: Window{1921ccf u0 johnse.test.speech/johnse.test.speech.UnityPlayerActivity}
2018-10-15 19:23:28.381 1102-1429/? W/InputDispatcher: Attempted to unregister already unregistered input channel '1921ccf johnse.test.speech/johnse.test.speech.UnityPlayerActivity (server)'
2018-10-15 19:23:28.381 710-710/? I/Zygote: Process 16832 exited cleanly (1)
2018-10-15 19:23:28.385 1102-1120/? W/ActivityManager: Force removing ActivityRecord{2954ccd u0 johnse.test.speech/.UnityPlayerActivity t24}: app died, no saved state
2018-10-15 19:23:28.392 1102-1135/? W/ActivityManager: setHasOverlayUi called on unknown pid: 16832
2018-10-15 19:23:28.424 607-607/? D/SurfaceFlinger: duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
2018-10-15 19:23:28.426 1324-1324/? I/Elmyra/ElmyraService: Unblocked; current action: SetupWizardAction
2018-10-15 19:23:28.433 755-798/? I/ASH: @ 436987.500: ccb_proximityInit: PROX initialized w/initData
2018-10-15 19:23:28.437 31613-31613/? W/SessionLifecycleManager: Handover failed. Creating new session controller.
2018-10-15 19:23:28.441 31613-31613/? I/OptInState: There is a new client and it does not support opt-in. Dropping request.
2018-10-15 19:23:28.444 1401-1401/? I/WallpaperService: engine resumed
2018-10-15 19:23:28.451 755-798/? D/CHRE: @ 436987.500: +: id 10, otherClientPresent 1, mode 3
2018-10-15 19:23:28.452 724-1252/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
2018-10-15 19:23:28.452 724-1252/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
2018-10-15 19:23:28.452 1102-1120/? I/WifiService: getConnectionInfo uid=10046
2018-10-15 19:23:28.453 724-7254/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
2018-10-15 19:23:28.453 1102-1120/? I/WifiService: getWifiEnabledState uid=10046
2018-10-15 19:23:28.453 31613-16919/? W/Settings: Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
2018-10-15 19:23:28.453 755-798/? D/CHRE: @ 436987.500: [ImuCal] Dynamic sensor configuration: high-performance.
2018-10-15 19:23:28.453 755-798/? D/CHRE: @ 436987.500: sensorType 9 allowed 1: mergedMode 3, otherClientPresent 1
2018-10-15 19:23:28.453 755-798/? D/CHRE: @ 436987.500: sensorType 11 allowed 1: mergedMode 3, otherClientPresent 1
2018-10-15 19:23:28.454 755-798/? D/CHRE: @ 436987.500: sensorType 13 allowed 0: mergedMode 3, otherClientPresent 0
2018-10-15 19:23:28.454 1102-1446/? I/WifiService: getConnectionInfo uid=10046
2018-10-15 19:23:28.455 1102-1446/? I/WifiService: getWifiEnabledState uid=10046
2018-10-15 19:23:28.455 31613-16918/? W/Settings: Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
2018-10-15 19:23:28.462 31613-31613/? W/CRChildManagerHelper: Trying to restore children after changes have been made to the child manager
2018-10-15 19:23:28.462 31613-31613/? W/CRChildManagerHelper: Trying to restore children after changes have been made to the child manager
2018-10-15 19:23:28.463 31613-16250/? E/EntrySyncManager: Cannot determine account name: drop request

NOTE **** This exception does seem to always occur, but it seems more related to Google Services
I will note that this phone does not have a SIM and does not have a user logged in. However, it is running with guest access MSFTGUEST WiFi ***

2018-10-15 19:23:28.464 31613-16250/? E/NowController: Failed to access data from EntryProvider to update foreground actions.
    java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not complete scheduled request to refresh entries. ClientErrorCode: 3
        at com.google.common.util.concurrent.d.da(SourceFile:85)
        at com.google.common.util.concurrent.d.get(SourceFile:23)
        at com.google.common.util.concurrent.l.get(SourceFile:2)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.aj.bas(SourceFile:15)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.aj.doInBackground(SourceFile:40)
        at com.google.android.apps.gsa.shared.util.concurrent.d.call(SourceFile:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.apps.gsa.shared.util.concurrent.a.ag.run(Unknown Source:4)
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4)
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.google.android.apps.gsa.shared.util.concurrent.a.ak.run(SourceFile:6)
     Caused by: java.lang.RuntimeException: Could not complete scheduled request to refresh entries. ClientErrorCode: 3
        at com.google.android.apps.gsa.sidekick.main.i.u.ak(SourceFile:6)
        at com.google.common.util.concurrent.q.P(SourceFile:7)
        at com.google.common.util.concurrent.p.run(SourceFile:37)
        at com.google.common.util.concurrent.br.execute(SourceFile:3)
        at com.google.common.util.concurrent.d.a(SourceFile:264)
        at com.google.common.util.concurrent.d.addListener(SourceFile:134)
        at com.google.common.util.concurrent.p.b(SourceFile:3)
        at com.google.common.util.concurrent.ax.a(SourceFile:18)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:10)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:7)
        at com.google.android.apps.gsa.sidekick.main.i.r.a(SourceFile:15)
        at com.google.android.apps.gsa.sidekick.main.i.s.ak(SourceFile:8)
        at com.google.common.util.concurrent.q.P(SourceFile:7)
        at com.google.common.util.concurrent.p.run(SourceFile:37)
        at com.google.common.util.concurrent.br.execute(SourceFile:3)
        at com.google.common.util.concurrent.d.a(SourceFile:264)
        at com.google.common.util.concurrent.d.addListener(SourceFile:134)
        at com.google.common.util.concurrent.p.b(SourceFile:3)
        at com.google.common.util.concurrent.ax.a(SourceFile:18)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:10)
        at com.google.android.apps.gsa.shared.util.concurrent.h.a(SourceFile:7)
        at com.google.android.apps.gsa.sidekick.main.i.r.a(SourceFile:10)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.aj.bas(SourceFile:14)
        at com.google.android.apps.gsa.staticplugins.nowstream.b.a.aj.doInBackground(SourceFile:40) 
        at com.google.android.apps.gsa.shared.util.concurrent.d.call(SourceFile:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.ag.run(Unknown Source:4) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.bo.run(SourceFile:4) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
        at com.google.android.apps.gsa.shared.util.concurrent.a.ak.run(SourceFile:6) 
2018-10-15 19:23:28.464 31613-16601/? W/LocationOracle: No location history returned by ContextManager
2018-10-15 19:23:28.466 31613-31613/? I/MicroDetectionWorker: #updateMicroDetector [detectionMode: [mDetectionMode: [1]]]
2018-10-15 19:23:28.466 31613-31613/? I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
2018-10-15 19:23:28.469 31613-15793/? I/MicroRecognitionRunner: Starting detection.
2018-10-15 19:23:28.469 31613-16919/? I/MicrophoneInputStream: mic_starting com.google.android.apps.gsa.speech.audio.af@367cf51
2018-10-15 19:23:28.470 724-7254/? W/DeviceHAL: Device 0xe8ab4000 open_input_stream: Invalid argument
2018-10-15 19:23:28.473 807-16921/? I/AudioFlinger: AudioFlinger's thread 0xeaa94180 tid=16921 ready to run
2018-10-15 19:23:28.478 31613-16919/? I/MicrophoneInputStream: mic_started com.google.android.apps.gsa.speech.audio.af@367cf51
2018-10-15 19:23:28.479 18317-16851/? W/ctxmgr: [AclManager]No 3 for (accnt=account#-517948760#, com.google.android.gms(10019):UserVelocityProducer, vrsn=14366028, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 18317). Was: 3 for 1, account#-517948760#
2018-10-15 19:23:28.481 31613-31613/? I/MicroDetectionWorker: onReady
2018-10-15 19:23:28.481 755-798/? I/ASH: @ 436987.531: ccb_proximityHandle: PRX_STATE_BEGIN
2018-10-15 19:23:28.482 755-798/? I/ASH: @ 436987.531: ccb_proximityHandle: initial state farAway
2018-10-15 19:23:28.484 724-16922/? D/sound_trigger_platform: platform_stdev_check_and_update_concurrency: concurrency active 0, tx 1, rx 0, concurrency session_allowed 0
2018-10-15 19:23:28.484 724-16922/? D/audio_hw_primary: enable_snd_device: snd_device(75: voice-rec-mic)
2018-10-15 19:23:28.484 724-16922/? D/audio_route: Apply path: voice-rec-mic
2018-10-15 19:23:28.484 2244-2249/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 0]
2018-10-15 19:23:28.489 31613-31613/? W/CRChildManagerHelper: Trying to restore children after changes have been made to the child manager
2018-10-15 19:23:28.489 31613-31613/? W/ErrorReporter: reportError [type: 29, code: 917507]: null
2018-10-15 19:23:28.489 31613-31613/? W/StreamController: Failed to get the restored children from restoreChildren.
2018-10-15 19:23:28.496 724-16922/? D/ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 41, path = 1, app id = 0x11132, sample rate = 48000
2018-10-15 19:23:28.496 724-16922/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
2018-10-15 19:23:28.496 724-16922/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
2018-10-15 19:23:28.496 724-16922/? D/ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 41, Topology Id 112fb
2018-10-15 19:23:28.496 724-16922/? D/ACDB-LOADER: Error: ACDB AFE returned = -19
2018-10-15 19:23:28.496 724-16922/? D/audio_hw_primary: enable_audio_route: usecase(9) apply and update mixer path: audio-record
2018-10-15 19:23:28.496 724-16922/? D/audio_route: Apply path: audio-record
2018-10-15 19:23:28.508 18317-18317/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.google.android.gms], packageName=null]
2018-10-15 19:23:28.509 18317-18317/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.google.android.gms], packageName=null]
2018-10-15 19:23:28.510 18317-16925/? I/PlaceInferenceEngine: [anon] Changed inference mode: 0
2018-10-15 19:23:28.526 18317-16851/? E/ctxmgr: [ProducerStatusImpl]updateStateForNewContextData: inactive, contextName=7
2018-10-15 19:23:28.549 18317-16925/? I/Places: ?: PlacesBleScanner start() with priority 2
2018-10-15 19:23:28.550 18317-16925/? I/PlaceInferenceEngine: [anon] Changed inference mode: 1
2018-10-15 19:23:28.555 18317-18317/? I/BeaconBle: Client requested scan, settings=BleSettings [scanMode=ZERO_POWER, callbackType=ALL_MATCHES, reportDelayMillis=0, 1 filters, 0 clients, callingClientName=Places]
2018-10-15 19:23:28.561 18317-16925/? I/Places: Converted 0 out of 47 WiFi scans
2018-10-15 19:23:28.561 18317-18317/? I/BeaconBle: ZERO_POWER is disabled.
2018-10-15 19:23:28.561 18317-18317/? I/BeaconBle: 'L' hardware scan: scan stopped, no powered clients
2018-10-15 19:23:28.561 1102-1720/? I/WifiService: getConnectionInfo uid=10019
2018-10-15 19:23:28.565 18317-16925/? I/PlaceInferenceEngine: [anon] Changed inference mode: 1
2018-10-15 19:23:28.566 31613-31613/? I/MicroDetectionWorker: onReady
2018-10-15 19:23:28.583 18317-16924/? I/PlaceInferenceEngine: No beacon scan available - ignoring candidates.

```
 - Error messages, log information, stack trace, ...
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by johnseghersmsft** [comment]
Upgrading to Android Pie (v9), I get a bit more insight into the crash: it appears that something in recognizeOnceAsync() is expecting an object of a type it isn't at SpeechRecognizer.java line 152.

```
10-16 16:15:02.666 15687 15687 D Unity:SpeechEngine: Starting Speech Recognition
10-16 16:15:02.667 15687 15687 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-16 16:15:02.668 15687 15687 E AndroidRuntime: FATAL EXCEPTION: main
10-16 16:15:02.668 15687 15687 E AndroidRuntime: Process: johnse.test.speech, PID: 15687
10-16 16:15:02.668 15687 15687 E AndroidRuntime: java.lang.BootstrapMethodError: Exception from call site #8 bootstrap method
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at com.microsoft.cognitiveservices.speech.SpeechRecognizer.recognizeOnceAsync(SpeechRecognizer.java:152)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at SpeechEngine.StartRecognitionUI(SpeechEngine.java:103)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at SpeechEngine$1.run(SpeechEngine.java:62)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-16 16:15:02.668 15687 15687 E AndroidRuntime: Caused by: java.lang.ClassCastException: Bootstrap method returned null
10-16 16:15:02.668 15687 15687 E AndroidRuntime: 	... 10 more
10-16 16:14:56.424 15687 15707 I chatty  : uid=10127(johnse.test.speech) identical 14 lines
10-16 16:14:56.424 15687 15707 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
10-16 16:15:02.671  1193  3508 W ActivityManager:   Force finishing activity johnse.test.speech/.UnityPlayerActivity
10-16 16:15:02.674 15687 15687 I Process : Sending signal. PID: 15687 SIG: 9
10-16 16:15:02.677  1193  1217 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-16 16:15:02.677  1193  1217 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-16 16:15:02.680   830   830 E lowmemorykiller: Error writing /proc/15687/oom_score_adj; errno=22
10-16 16:15:02.700  1193  1613 W InputDispatcher: channel '63b0fce johnse.test.speech/johnse.test.speech.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-16 16:15:02.700  1193  1613 E InputDispatcher: channel '63b0fce johnse.test.speech/johnse.test.speech.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 16:15:02.700  1193  5180 I MediaFocusControl: AudioFocus  removeFocusStackEntryOnDeath(): removing entry for android.os.BinderProxy@675719a
10-16 16:15:02.701  1193  5180 I ActivityManager: Process johnse.test.speech (pid 15687) has died: vis  +99TOP 
10-16 16:15:02.701  1193  1203 I WindowManager: WIN DEATH: Window{63b0fce u0 johnse.test.speech/johnse.test.speech.UnityPlayerActivity}
10-16 16:15:02.701  1193  1203 W InputDispatcher: Attempted to unregister already unregistered input channel '63b0fce johnse.test.speech/johnse.test.speech.UnityPlayerActivity (server)'
10-16 16:15:02.701   774   774 I Zygote  : Process 15687 exited due to signal (9)
10-16 16:15:02.702  1193  1220 W libprocessgroup: kill(-15687, 9) failed: No such process
10-16 16:15:02.702  1193  1220 I libprocessgroup: Successfully killed process cgroup uid 10127 pid 15687 in 0ms
10-16 16:15:02.702  1969  2577 E bt_btif : register_notification_rsp: Avrcp device is not connected, handle: 0x0
10-16 16:15:02.703  1969  2577 I chatty  : uid=1002(bluetooth) BluetoothAvrcpH identical 4 lines
10-16 16:15:02.703  1969  2577 E bt_btif : register_notification_rsp: Avrcp device is not connected, handle: 0x0
10-16 16:15:02.706   608   608 E HWComposer: presentAndGetReleaseFences: present failed for display 0: NotValidated (7)
10-16 16:15:02.707   608   702 W SurfaceFlinger: Attempting to set client state on removed layer: johnse.test.speech/johnse.test.speech.UnityPlayerActivity#0
10-16 16:15:02.707   608   702 W SurfaceFlinger: Attempting to destroy on removed layer: johnse.test.speech/johnse.test.speech.UnityPlayerActivity#0
10-16 16:15:02.710   799   799 D android.hardware.power@1.2-service.wahoo-libperfmgr: AUDIO STREAMING OFF
10-16 16:15:02.713  1193  1225 W ActivityManager: setHasOverlayUi called on unknown pid: 15687
10-16 16:15:02.723   608   608 E HWComposer: presentAndGetReleaseFences: present failed for display 0: NotValidated (7)
10-16 16:15:02.726   793   793 I /vendor/bin/hw/android.hardware.health@2.0-service.wahoo: SRAM data: 2805000
```

**Comment by fmegen** [comment]
We haven't yet tested the Speech SDK with Android Pie or Unity.

Just to be sure there are no issues with your Android version, could you please try to deploy/run the Android quickstart on your device to verify that this works for you.

Does the quickstart run/recognize?

kind regards,
 friedel

**Comment by johnseghersmsft** [comment]
I tracked it down to the use of lambdas in the API calls. This requires Source and Target versions to be set to Java 1.8 in Android Studio.
