### ISSUE TITLE
NodeJS speechSynthesizer "window is not defined"

### ISSUE THREAD

**Issue by binarythinktank** [Azure-Samples/cognitive-services-speech-sdk#782]
**Describe the bug**
trying to synthesize speech but its giving me a window not defined error.
i was following the quickstart and the example for nodejs here on git (synthesize.js)

**To Reproduce**
const azuretts = require('microsoft-cognitiveservices-speech-sdk');
const speechConfig = azuretts.SpeechConfig.fromSubscription(azureKey, azureRegion);
speechConfig.speechSynthesisLanguage = azureLanguage;
speechConfig.speechSynthesisVoiceName = azureVoiceName;

const synthesizer = new azuretts.SpeechSynthesizer(speechConfig, undefined);
> ReferenceError: window is not defined

**Expected behavior**
create a speechSynthesizer object so i can get the resulting audio as a buffer in Nodejs (i dont want file or speaker output)

**Version of the Cognitive Services Speech SDK**
1.13.1

**Platform, Operating System, and Programming Language**
nodejs 12 on aws lambda

**Additional context**
 ReferenceError: window is not defined
    at SpeakerAudioDestination.set [as format] (/var/task/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/SpeakerAudioDestination.js:65:66)
    at AudioOutputConfigImpl.set [as format] (/var/task/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/Audio/AudioConfig.js:301:41)
    at SynthesisAdapterBase.set [as audioOutputFormat] (/var/task/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.speech/SynthesisAdapterBase.js:212:57)
    at SpeechSynthesizer.implCommonSynthesizeSetup (/var/task/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:275:44)
    at new SpeechSynthesizer (/var/task/node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/sdk/SpeechSynthesizer.js:35:14)
    at /var/task/index.js:320:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by pankopon** [comment]
@yulin-li Can you please check?

**Comment by yulin-li** [comment]
@binarythinktank This is a bug of SDK, you can use `const synthesizer = new azuretts.SpeechSynthesizer(speechConfig, null);` as a workaround. see https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/227
