### ISSUE TITLE
No module named '_speech_py_impl  in azure.cognitiveservices.speech 

### ISSUE THREAD

**Issue by arvind2k** [Azure-Samples/cognitive-services-speech-sdk#792]
I am trying to upload azure funtion in Python on windows 10. In the first lines of code, it returns an error because of the following line:
import azure.cognitiveservices.speech as speechsdk  
  File "...importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level) ModuleNotFoundError: No module named '_speech_py_impl'
I have installed sdk by:  pip install azure-cognitiveservices-speech
by adding import azure.cognitiveservices.speech as speechsdk  line in code it throws error 
Detail error message: 
Traceback (most recent call last):
  File "C:\...\env\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 27, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "voice_read_azure.py", line 1, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "C:\....\lib\site-packages\azure\cognitiveservices\speech\__init__.py", line 8, in <module>
    from .speech import *
  File "C:\...\lib\site-packages\azure\cognitiveservices\speech\speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "C:\....\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 33, in <module>
    _speech_py_impl = swig_import_helper()
  File "C:\.....\lib\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 31, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_speech_py_impl'

**Comment by jhakulin** [comment]
@arvind2k Thanks for feedback, could it be possible to share your project or minimal sample for it?

**Comment by arvind2k** [comment]
Hi Jarno,

 

We are using sample code mentioned in help file. If we add a simple one liner 

import azure.cognitiveservices.speech as speechsdk

 

and try to execute the code it throws error.

 

Traceback (most recent call last):

  File "C:\Users\Arvind\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 27, in swig_import_helper

    return importlib.import_module(mname)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 583, in module_from_spec

  File "<frozen importlib._bootstrap_external>", line 1043, in create_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

ImportError: DLL load failed: The specified module could not be found.

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "voice_read_azure.py", line 2, in <module>

    import azure.cognitiveservices.speech as speechsdk

  File "C:\.......AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\cognitiveservices\speech\__init__.py", line 8, in <module>

    from .speech import *

  File "C:\......AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\cognitiveservices\speech\speech.py", line 8, in <module>

    from . import speech_py_impl as impl

  File "C:\......AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 33, in <module>

    _speech_py_impl = swig_import_helper()

  File "C:\......AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\azure\cognitiveservices\speech\speech_py_impl.py", line 31, in swig_import_helper

    return importlib.import_module('_speech_py_impl')

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_speech_py_impl'

 

 

I have tried same on ec2 instance and received same error.

 

 

import azure.cognitiveservices.speech as speechsdk

 

speech_key = "***************" 

service_region = "australiaeast"

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

 

audio_filename  = "myVoiceIsMyPassportVerifyMe01.wav"

print(audio_filename)

 

def speech_recognize_once_from_file():   

    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

    print("speech_recognize_once_from_file...")

    audio_config = speechsdk.audio.AudioConfig(filename=audio_filename)

    # Creates a speech recognizer using a file as audio input, also specify the speech language

    speech_recognizer = speechsdk.SpeechRecognizer(

        speech_config=speech_config, language="en-GB", audio_config=audio_config)

 

    print("Recognizing first result...")

 

    # Starts speech recognition, and returns after a single utterance is recognized. The end of a  # single utterance is determined by listening for silence at the end or until a maximum of 15

    # seconds of audio is processed. It returns the recognition text as result.  # Note: Since recognize_once() returns only a single utterance, it is suitable only for single

    # shot recognition like command or query.    # For long-running multi-utterance recognition, use start_continuous_recognition() instead.

    result = speech_recognizer.recognize_once()

 

    # Check the result

    if result.reason == speechsdk.ResultReason.RecognizedSpeech:

        print("Recognized: {}".format(result.text))

    elif result.reason == speechsdk.ResultReason.NoMatch:

        print("No speech could be recognized: {}".format(result.no_match_details))

    elif result.reason == speechsdk.ResultReason.Canceled:

        cancellation_details = result.cancellation_details

        print("Speech Recognition canceled: {}".format(cancellation_details.reason))

        if cancellation_details.reason == speechsdk.CancellationReason.Error:

            print("Error details: {}".format(cancellation_details.error_details))

    # </SpeechRecognitionWithFile>

 

 

 

 

 

Regards

 

Arvind Kumar

**Comment by jhakulin** [comment]
@arvind2k Are you using VSCode for Azure functions development? 
I followed instructions below to create Azure function project on VSCode and Speech SDK v1.13.0 on Python Azure function was working OK locally and when executed in the Azure cloud.
https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-01
Could you please share the output of your project when you do "Attach to Python functions" ?
Please make sure your project meets the prerequisites for Python, I used Python 3.8.5 64-bit on venv.

**Comment by arvind2k** [comment]
Hi Hakulinen,

 

Thanks for your reply. 

 

No I am not using VSCode for Azure functions development. I am using notepad + and  VS code as a only editor. I have followed steps from 

 <https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=script%2Cwindowsinstall&pivots=programming-language-python> https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=script%2Cwindowsinstall&pivots=programming-language-python

 

on cmd prompt, I have install  speech SDK by using, pip install azure-cognitiveservices-speech. Please check below screen shot for your reference.
 
Then trying to execute the code by using python or python3 <filename>
 


 

With Regards

Arvind Kumar

**Comment by jhakulin** [comment]
@arvind2k  The quickstarts you shared are not describing all the steps to create Azure functions (we will add separate docs for that in the future). I understood you see this problem when uploading the script to Azure function. Do you see the issue also with normal python quickstart when running the python script locally as described in the quickstart below ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=script%2Cwindowsinstall&pivots=programming-language-python

**Comment by jhakulin** [comment]
@arvind2k The Speech SDK on Windows depends on the shared Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019. Could you make sure you have installed it from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

And let us know if this helps.

**Comment by pankopon** [comment]
Closed since no further update, presumed resolved by installing the latest Visual C++ runtimes. Please open a new issue if you need more support.

**Comment by nitish-dewan** [comment]
> Closed since no further update, presumed resolved by installing the latest Visual C++ runtimes. Please open a new issue if you need more support.

Working fine after installing 201-2019 Visual C++ Runtime!
