### ISSUE TITLE
ReferenceError: FileReader is not defined for AudioConfig.fromWavFileInput(filename) NodeJS

### ISSUE THREAD

**Issue by Ad1tyaV** [Azure-Samples/cognitive-services-speech-sdk#833]
```
>node s2t.js
[]
F:\testings2t\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\FileAudioSource.js:72
            var headerReader = new FileReader();
                               ^

ReferenceError: FileReader is not defined
    at FileAudioSource.readHeader (F:\testings2t\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\FileAudioSource.js:72:32)
    at new FileAudioSource (F:\testings2t\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\FileAudioSource.js:136:44)
    at Function.AudioConfig.fromWavFileInput (F:\testings2t\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\sdk\Audio\AudioConfig.js:65:36)
    at Object.<anonymous> (F:\testings2t\s2t.js:21:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```
This is supposed to work according to the docs, anything I'm missing, below line seems to be initiating the above error

`const audioConfig = speechsdk.AudioConfig.fromWavFileInput(filename="katiesteve.wav")`

**Comment by rhurey** [comment]
The FileReader class is a browser construct, and not in NodeJs.

Only having a single overload of fromWaveFileInput has to do with the path the SDK took being browser only first and later supporting node. When node support was introduced, an overload for fromWaveFileInput that took a file path wasn't added, and is in our backlog.
