### ISSUE TITLE
RuntimeException while trying to release SpeechRecognizer

### ISSUE THREAD

**Issue by rahul-ravindra** [Azure-Samples/cognitive-services-speech-sdk#841]
**Describe the bug**
Trying to release the SpeechRecognizer on Activity destroy lifecycle while the recognition is happening is causing runtime exceptions. This throws IllegalStateException from activity during destroy.
We are using ``` speechRecognizer.recognizeOnceAsync() ```  for recognition.

**To Reproduce**
1. On button click we call ``` speechRecognizer.recognizeOnceAsync() ``` and when we move to a different screen we try
releasing with  ``` speechRecognizer.close() ``` which is called in ``` onPause() ``` lifecycle of Activity

**Expected behavior**
It should have canceled the recognition and given priority to release. Or is there a way safe way to stop recognition and release

**Version of the Cognitive Services Speech SDK**
1.12.1

**Platform, Operating System, and Programming Language**
 - OS: Android
 - Hardware - x64, x86, ARM, 
 - Programming language: Java
 
**Additional context**
```
Caused by java.lang.IllegalStateException: Cannot dispose a recognizer while async recognition is running. Await async recognitions to avoid unexpected disposals.
       at com.microsoft.cognitiveservices.speech.Recognizer.close(Recognizer.java:78)
       at com.byjus.ela.repositories.speech.microsoft.MicrosoftSpeechRecognitionManager.close(MicrosoftSpeechRecognitionManager.java:144)
       at com.byjus.ela.repositories.speech.SpeechRecognitionRepository.stopAudioRecognition(SpeechRecognitionRepository.java:69)
       at com.byjus.ela.repositories.speech.SpeechRecognitionRepository.stopSpeechRecognition(SpeechRecognitionRepository.java:56)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to pause activity {com.byjus.tle/com.byjus.ela.home.view.HomeActivity}: java.lang.IllegalStateException: Cannot dispose a recognizer while async recognition is running. Await async recognitions to avoid unexpected disposals.
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4194)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4149)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4101)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
```

**Comment by glharper** [comment]
@rahul-ravindra As an asynchronous method, you should probably wait for the completed task of recognizeOnceAsync() before performing other operations on the speechRecognizer object. If you absolutely must destroy everything, call stopContinuousRecognitionAsync(), but that is asynchronous and the completed task for that call also must be awaited. So I'd recommend:```

                final Future<Void> task = reco.recognizeOnceAsync();
                setOnTaskCompletedListener(task, result -> {
                    // some external event has happened, and closeReco has been set to true
                    if (closeReco) {
                        reco.close();
                    };
                });
```

**Comment by glecaros** [comment]
Closing this as there hasn't been any activity in a while. @rahul-ravindra feel free to reopen if you need more help.
